// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ticket/v1/ticket_service.proto

package ticketv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketService_CreateTicketProvider_FullMethodName = "/ticket.v1.TicketService/CreateTicketProvider"
	TicketService_GetTicketProvider_FullMethodName    = "/ticket.v1.TicketService/GetTicketProvider"
	TicketService_ListTicketProviders_FullMethodName  = "/ticket.v1.TicketService/ListTicketProviders"
	TicketService_UpdateTicketProvider_FullMethodName = "/ticket.v1.TicketService/UpdateTicketProvider"
	TicketService_DeleteTicketProvider_FullMethodName = "/ticket.v1.TicketService/DeleteTicketProvider"
	TicketService_TestTicketProvider_FullMethodName   = "/ticket.v1.TicketService/TestTicketProvider"
	TicketService_CreateTicket_FullMethodName         = "/ticket.v1.TicketService/CreateTicket"
	TicketService_GetTicket_FullMethodName            = "/ticket.v1.TicketService/GetTicket"
	TicketService_ListTickets_FullMethodName          = "/ticket.v1.TicketService/ListTickets"
	TicketService_UpdateTicket_FullMethodName         = "/ticket.v1.TicketService/UpdateTicket"
	TicketService_SyncTicketStatus_FullMethodName     = "/ticket.v1.TicketService/SyncTicketStatus"
)

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TicketService provides ticket management operations for external ticketing system integration.
type TicketServiceClient interface {
	// Provider management
	CreateTicketProvider(ctx context.Context, in *CreateTicketProviderRequest, opts ...grpc.CallOption) (*TicketProvider, error)
	GetTicketProvider(ctx context.Context, in *GetTicketProviderRequest, opts ...grpc.CallOption) (*TicketProvider, error)
	ListTicketProviders(ctx context.Context, in *ListTicketProvidersRequest, opts ...grpc.CallOption) (*ListTicketProvidersResponse, error)
	UpdateTicketProvider(ctx context.Context, in *UpdateTicketProviderRequest, opts ...grpc.CallOption) (*TicketProvider, error)
	DeleteTicketProvider(ctx context.Context, in *DeleteTicketProviderRequest, opts ...grpc.CallOption) (*DeleteTicketProviderResponse, error)
	TestTicketProvider(ctx context.Context, in *TestTicketProviderRequest, opts ...grpc.CallOption) (*TestTicketProviderResponse, error)
	// Ticket management
	CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*Ticket, error)
	GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*Ticket, error)
	ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error)
	UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*Ticket, error)
	SyncTicketStatus(ctx context.Context, in *SyncTicketStatusRequest, opts ...grpc.CallOption) (*SyncTicketStatusResponse, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) CreateTicketProvider(ctx context.Context, in *CreateTicketProviderRequest, opts ...grpc.CallOption) (*TicketProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketProvider)
	err := c.cc.Invoke(ctx, TicketService_CreateTicketProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetTicketProvider(ctx context.Context, in *GetTicketProviderRequest, opts ...grpc.CallOption) (*TicketProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketProvider)
	err := c.cc.Invoke(ctx, TicketService_GetTicketProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ListTicketProviders(ctx context.Context, in *ListTicketProvidersRequest, opts ...grpc.CallOption) (*ListTicketProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketProvidersResponse)
	err := c.cc.Invoke(ctx, TicketService_ListTicketProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UpdateTicketProvider(ctx context.Context, in *UpdateTicketProviderRequest, opts ...grpc.CallOption) (*TicketProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketProvider)
	err := c.cc.Invoke(ctx, TicketService_UpdateTicketProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) DeleteTicketProvider(ctx context.Context, in *DeleteTicketProviderRequest, opts ...grpc.CallOption) (*DeleteTicketProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTicketProviderResponse)
	err := c.cc.Invoke(ctx, TicketService_DeleteTicketProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) TestTicketProvider(ctx context.Context, in *TestTicketProviderRequest, opts ...grpc.CallOption) (*TestTicketProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestTicketProviderResponse)
	err := c.cc.Invoke(ctx, TicketService_TestTicketProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*Ticket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ticket)
	err := c.cc.Invoke(ctx, TicketService_CreateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*Ticket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ticket)
	err := c.cc.Invoke(ctx, TicketService_GetTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketsResponse)
	err := c.cc.Invoke(ctx, TicketService_ListTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*Ticket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ticket)
	err := c.cc.Invoke(ctx, TicketService_UpdateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) SyncTicketStatus(ctx context.Context, in *SyncTicketStatusRequest, opts ...grpc.CallOption) (*SyncTicketStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncTicketStatusResponse)
	err := c.cc.Invoke(ctx, TicketService_SyncTicketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations must embed UnimplementedTicketServiceServer
// for forward compatibility.
//
// TicketService provides ticket management operations for external ticketing system integration.
type TicketServiceServer interface {
	// Provider management
	CreateTicketProvider(context.Context, *CreateTicketProviderRequest) (*TicketProvider, error)
	GetTicketProvider(context.Context, *GetTicketProviderRequest) (*TicketProvider, error)
	ListTicketProviders(context.Context, *ListTicketProvidersRequest) (*ListTicketProvidersResponse, error)
	UpdateTicketProvider(context.Context, *UpdateTicketProviderRequest) (*TicketProvider, error)
	DeleteTicketProvider(context.Context, *DeleteTicketProviderRequest) (*DeleteTicketProviderResponse, error)
	TestTicketProvider(context.Context, *TestTicketProviderRequest) (*TestTicketProviderResponse, error)
	// Ticket management
	CreateTicket(context.Context, *CreateTicketRequest) (*Ticket, error)
	GetTicket(context.Context, *GetTicketRequest) (*Ticket, error)
	ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error)
	UpdateTicket(context.Context, *UpdateTicketRequest) (*Ticket, error)
	SyncTicketStatus(context.Context, *SyncTicketStatusRequest) (*SyncTicketStatusResponse, error)
	mustEmbedUnimplementedTicketServiceServer()
}

// UnimplementedTicketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketServiceServer struct{}

func (UnimplementedTicketServiceServer) CreateTicketProvider(context.Context, *CreateTicketProviderRequest) (*TicketProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicketProvider not implemented")
}
func (UnimplementedTicketServiceServer) GetTicketProvider(context.Context, *GetTicketProviderRequest) (*TicketProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketProvider not implemented")
}
func (UnimplementedTicketServiceServer) ListTicketProviders(context.Context, *ListTicketProvidersRequest) (*ListTicketProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTicketProviders not implemented")
}
func (UnimplementedTicketServiceServer) UpdateTicketProvider(context.Context, *UpdateTicketProviderRequest) (*TicketProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketProvider not implemented")
}
func (UnimplementedTicketServiceServer) DeleteTicketProvider(context.Context, *DeleteTicketProviderRequest) (*DeleteTicketProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTicketProvider not implemented")
}
func (UnimplementedTicketServiceServer) TestTicketProvider(context.Context, *TestTicketProviderRequest) (*TestTicketProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestTicketProvider not implemented")
}
func (UnimplementedTicketServiceServer) CreateTicket(context.Context, *CreateTicketRequest) (*Ticket, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicket not implemented")
}
func (UnimplementedTicketServiceServer) GetTicket(context.Context, *GetTicketRequest) (*Ticket, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicket not implemented")
}
func (UnimplementedTicketServiceServer) ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTickets not implemented")
}
func (UnimplementedTicketServiceServer) UpdateTicket(context.Context, *UpdateTicketRequest) (*Ticket, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicket not implemented")
}
func (UnimplementedTicketServiceServer) SyncTicketStatus(context.Context, *SyncTicketStatusRequest) (*SyncTicketStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncTicketStatus not implemented")
}
func (UnimplementedTicketServiceServer) mustEmbedUnimplementedTicketServiceServer() {}
func (UnimplementedTicketServiceServer) testEmbeddedByValue()                       {}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	// If the following call panics, it indicates UnimplementedTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_CreateTicketProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).CreateTicketProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_CreateTicketProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).CreateTicketProvider(ctx, req.(*CreateTicketProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetTicketProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetTicketProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetTicketProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetTicketProvider(ctx, req.(*GetTicketProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ListTicketProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ListTicketProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ListTicketProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ListTicketProviders(ctx, req.(*ListTicketProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UpdateTicketProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UpdateTicketProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UpdateTicketProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UpdateTicketProvider(ctx, req.(*UpdateTicketProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_DeleteTicketProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTicketProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).DeleteTicketProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_DeleteTicketProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).DeleteTicketProvider(ctx, req.(*DeleteTicketProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_TestTicketProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestTicketProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).TestTicketProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_TestTicketProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).TestTicketProvider(ctx, req.(*TestTicketProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_CreateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).CreateTicket(ctx, req.(*CreateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetTicket(ctx, req.(*GetTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ListTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ListTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ListTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ListTickets(ctx, req.(*ListTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UpdateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UpdateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UpdateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UpdateTicket(ctx, req.(*UpdateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_SyncTicketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTicketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).SyncTicketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_SyncTicketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).SyncTicketStatus(ctx, req.(*SyncTicketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.v1.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicketProvider",
			Handler:    _TicketService_CreateTicketProvider_Handler,
		},
		{
			MethodName: "GetTicketProvider",
			Handler:    _TicketService_GetTicketProvider_Handler,
		},
		{
			MethodName: "ListTicketProviders",
			Handler:    _TicketService_ListTicketProviders_Handler,
		},
		{
			MethodName: "UpdateTicketProvider",
			Handler:    _TicketService_UpdateTicketProvider_Handler,
		},
		{
			MethodName: "DeleteTicketProvider",
			Handler:    _TicketService_DeleteTicketProvider_Handler,
		},
		{
			MethodName: "TestTicketProvider",
			Handler:    _TicketService_TestTicketProvider_Handler,
		},
		{
			MethodName: "CreateTicket",
			Handler:    _TicketService_CreateTicket_Handler,
		},
		{
			MethodName: "GetTicket",
			Handler:    _TicketService_GetTicket_Handler,
		},
		{
			MethodName: "ListTickets",
			Handler:    _TicketService_ListTickets_Handler,
		},
		{
			MethodName: "UpdateTicket",
			Handler:    _TicketService_UpdateTicket_Handler,
		},
		{
			MethodName: "SyncTicketStatus",
			Handler:    _TicketService_SyncTicketStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticket/v1/ticket_service.proto",
}
