// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ticket/v1/ticket_service.proto

package ticketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTicketProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *TicketProvider        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketProviderRequest) Reset() {
	*x = CreateTicketProviderRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketProviderRequest) ProtoMessage() {}

func (x *CreateTicketProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketProviderRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTicketProviderRequest) GetProvider() *TicketProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type GetTicketProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketProviderRequest) Reset() {
	*x = GetTicketProviderRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketProviderRequest) ProtoMessage() {}

func (x *GetTicketProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketProviderRequest.ProtoReflect.Descriptor instead.
func (*GetTicketProviderRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTicketProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTicketProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	EnabledOnly   bool                   `protobuf:"varint,3,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketProvidersRequest) Reset() {
	*x = ListTicketProvidersRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketProvidersRequest) ProtoMessage() {}

func (x *ListTicketProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListTicketProvidersRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTicketProvidersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTicketProvidersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTicketProvidersRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListTicketProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*TicketProvider      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketProvidersResponse) Reset() {
	*x = ListTicketProvidersResponse{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketProvidersResponse) ProtoMessage() {}

func (x *ListTicketProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListTicketProvidersResponse) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListTicketProvidersResponse) GetProviders() []*TicketProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ListTicketProvidersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTicketProvidersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateTicketProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *TicketProvider        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketProviderRequest) Reset() {
	*x = UpdateTicketProviderRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketProviderRequest) ProtoMessage() {}

func (x *UpdateTicketProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketProviderRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTicketProviderRequest) GetProvider() *TicketProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *UpdateTicketProviderRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteTicketProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketProviderRequest) Reset() {
	*x = DeleteTicketProviderRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketProviderRequest) ProtoMessage() {}

func (x *DeleteTicketProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteTicketProviderRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTicketProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTicketProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketProviderResponse) Reset() {
	*x = DeleteTicketProviderResponse{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketProviderResponse) ProtoMessage() {}

func (x *DeleteTicketProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteTicketProviderResponse) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTicketProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TestTicketProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestTicketProviderRequest) Reset() {
	*x = TestTicketProviderRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTicketProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTicketProviderRequest) ProtoMessage() {}

func (x *TestTicketProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTicketProviderRequest.ProtoReflect.Descriptor instead.
func (*TestTicketProviderRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{7}
}

func (x *TestTicketProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestTicketProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestTicketProviderResponse) Reset() {
	*x = TestTicketProviderResponse{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTicketProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTicketProviderResponse) ProtoMessage() {}

func (x *TestTicketProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTicketProviderResponse.ProtoReflect.Descriptor instead.
func (*TestTicketProviderResponse) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{8}
}

func (x *TestTicketProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestTicketProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestTicketProviderResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type CreateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTicketRequest) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTicketsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filters
	ProviderId    string `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	AlertId       string `protobuf:"bytes,4,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListTicketsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTicketsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTicketsRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ListTicketsRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *ListTicketsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTicketsRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListTicketsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTicketsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketRequest) Reset() {
	*x = UpdateTicketRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketRequest) ProtoMessage() {}

func (x *UpdateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTicketRequest) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *UpdateTicketRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type SyncTicketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTicketStatusRequest) Reset() {
	*x = SyncTicketStatusRequest{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTicketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTicketStatusRequest) ProtoMessage() {}

func (x *SyncTicketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTicketStatusRequest.ProtoReflect.Descriptor instead.
func (*SyncTicketStatusRequest) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{14}
}

func (x *SyncTicketStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SyncTicketStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ticket         *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Changed        bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,3,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncTicketStatusResponse) Reset() {
	*x = SyncTicketStatusResponse{}
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTicketStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTicketStatusResponse) ProtoMessage() {}

func (x *SyncTicketStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTicketStatusResponse.ProtoReflect.Descriptor instead.
func (*SyncTicketStatusResponse) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_service_proto_rawDescGZIP(), []int{15}
}

func (x *SyncTicketStatusResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *SyncTicketStatusResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *SyncTicketStatusResponse) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

var File_ticket_v1_ticket_service_proto protoreflect.FileDescriptor

const file_ticket_v1_ticket_service_proto_rawDesc = "" +
	"\n" +
	"\x1eticket/v1/ticket_service.proto\x12\tticket.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x16ticket/v1/ticket.proto\"T\n" +
	"\x1bCreateTicketProviderRequest\x125\n" +
	"\bprovider\x18\x01 \x01(\v2\x19.ticket.v1.TicketProviderR\bprovider\"*\n" +
	"\x18GetTicketProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x1aListTicketProvidersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12!\n" +
	"\fenabled_only\x18\x03 \x01(\bR\venabledOnly\"\x9f\x01\n" +
	"\x1bListTicketProvidersResponse\x127\n" +
	"\tproviders\x18\x01 \x03(\v2\x19.ticket.v1.TicketProviderR\tproviders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x91\x01\n" +
	"\x1bUpdateTicketProviderRequest\x125\n" +
	"\bprovider\x18\x01 \x01(\v2\x19.ticket.v1.TicketProviderR\bprovider\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"-\n" +
	"\x1bDeleteTicketProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x1cDeleteTicketProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x19TestTicketProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x1aTestTicketProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"@\n" +
	"\x13CreateTicketRequest\x12)\n" +
	"\x06ticket\x18\x01 \x01(\v2\x11.ticket.v1.TicketR\x06ticket\"\"\n" +
	"\x10GetTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc0\x01\n" +
	"\x12ListTicketsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\balert_id\x18\x04 \x01(\tR\aalertId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\"\x8b\x01\n" +
	"\x13ListTicketsResponse\x12+\n" +
	"\atickets\x18\x01 \x03(\v2\x11.ticket.v1.TicketR\atickets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"}\n" +
	"\x13UpdateTicketRequest\x12)\n" +
	"\x06ticket\x18\x01 \x01(\v2\x11.ticket.v1.TicketR\x06ticket\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\")\n" +
	"\x17SyncTicketStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x88\x01\n" +
	"\x18SyncTicketStatusResponse\x12)\n" +
	"\x06ticket\x18\x01 \x01(\v2\x11.ticket.v1.TicketR\x06ticket\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x12'\n" +
	"\x0fprevious_status\x18\x03 \x01(\tR\x0epreviousStatus2\xba\a\n" +
	"\rTicketService\x12Y\n" +
	"\x14CreateTicketProvider\x12&.ticket.v1.CreateTicketProviderRequest\x1a\x19.ticket.v1.TicketProvider\x12S\n" +
	"\x11GetTicketProvider\x12#.ticket.v1.GetTicketProviderRequest\x1a\x19.ticket.v1.TicketProvider\x12d\n" +
	"\x13ListTicketProviders\x12%.ticket.v1.ListTicketProvidersRequest\x1a&.ticket.v1.ListTicketProvidersResponse\x12Y\n" +
	"\x14UpdateTicketProvider\x12&.ticket.v1.UpdateTicketProviderRequest\x1a\x19.ticket.v1.TicketProvider\x12g\n" +
	"\x14DeleteTicketProvider\x12&.ticket.v1.DeleteTicketProviderRequest\x1a'.ticket.v1.DeleteTicketProviderResponse\x12a\n" +
	"\x12TestTicketProvider\x12$.ticket.v1.TestTicketProviderRequest\x1a%.ticket.v1.TestTicketProviderResponse\x12A\n" +
	"\fCreateTicket\x12\x1e.ticket.v1.CreateTicketRequest\x1a\x11.ticket.v1.Ticket\x12;\n" +
	"\tGetTicket\x12\x1b.ticket.v1.GetTicketRequest\x1a\x11.ticket.v1.Ticket\x12L\n" +
	"\vListTickets\x12\x1d.ticket.v1.ListTicketsRequest\x1a\x1e.ticket.v1.ListTicketsResponse\x12A\n" +
	"\fUpdateTicket\x12\x1e.ticket.v1.UpdateTicketRequest\x1a\x11.ticket.v1.Ticket\x12[\n" +
	"\x10SyncTicketStatus\x12\".ticket.v1.SyncTicketStatusRequest\x1a#.ticket.v1.SyncTicketStatusResponseB\xae\x01\n" +
	"\rcom.ticket.v1B\x12TicketServiceProtoP\x01ZDgithub.com/kneutral-org/alerting-system/pkg/proto/ticket/v1;ticketv1\xa2\x02\x03TXX\xaa\x02\tTicket.V1\xca\x02\tTicket\\V1\xe2\x02\x15Ticket\\V1\\GPBMetadata\xea\x02\n" +
	"Ticket::V1b\x06proto3"

var (
	file_ticket_v1_ticket_service_proto_rawDescOnce sync.Once
	file_ticket_v1_ticket_service_proto_rawDescData []byte
)

func file_ticket_v1_ticket_service_proto_rawDescGZIP() []byte {
	file_ticket_v1_ticket_service_proto_rawDescOnce.Do(func() {
		file_ticket_v1_ticket_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_v1_ticket_service_proto_rawDesc), len(file_ticket_v1_ticket_service_proto_rawDesc)))
	})
	return file_ticket_v1_ticket_service_proto_rawDescData
}

var file_ticket_v1_ticket_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_ticket_v1_ticket_service_proto_goTypes = []any{
	(*CreateTicketProviderRequest)(nil),  // 0: ticket.v1.CreateTicketProviderRequest
	(*GetTicketProviderRequest)(nil),     // 1: ticket.v1.GetTicketProviderRequest
	(*ListTicketProvidersRequest)(nil),   // 2: ticket.v1.ListTicketProvidersRequest
	(*ListTicketProvidersResponse)(nil),  // 3: ticket.v1.ListTicketProvidersResponse
	(*UpdateTicketProviderRequest)(nil),  // 4: ticket.v1.UpdateTicketProviderRequest
	(*DeleteTicketProviderRequest)(nil),  // 5: ticket.v1.DeleteTicketProviderRequest
	(*DeleteTicketProviderResponse)(nil), // 6: ticket.v1.DeleteTicketProviderResponse
	(*TestTicketProviderRequest)(nil),    // 7: ticket.v1.TestTicketProviderRequest
	(*TestTicketProviderResponse)(nil),   // 8: ticket.v1.TestTicketProviderResponse
	(*CreateTicketRequest)(nil),          // 9: ticket.v1.CreateTicketRequest
	(*GetTicketRequest)(nil),             // 10: ticket.v1.GetTicketRequest
	(*ListTicketsRequest)(nil),           // 11: ticket.v1.ListTicketsRequest
	(*ListTicketsResponse)(nil),          // 12: ticket.v1.ListTicketsResponse
	(*UpdateTicketRequest)(nil),          // 13: ticket.v1.UpdateTicketRequest
	(*SyncTicketStatusRequest)(nil),      // 14: ticket.v1.SyncTicketStatusRequest
	(*SyncTicketStatusResponse)(nil),     // 15: ticket.v1.SyncTicketStatusResponse
	(*TicketProvider)(nil),               // 16: ticket.v1.TicketProvider
	(*fieldmaskpb.FieldMask)(nil),        // 17: google.protobuf.FieldMask
	(*Ticket)(nil),                       // 18: ticket.v1.Ticket
}
var file_ticket_v1_ticket_service_proto_depIdxs = []int32{
	16, // 0: ticket.v1.CreateTicketProviderRequest.provider:type_name -> ticket.v1.TicketProvider
	16, // 1: ticket.v1.ListTicketProvidersResponse.providers:type_name -> ticket.v1.TicketProvider
	16, // 2: ticket.v1.UpdateTicketProviderRequest.provider:type_name -> ticket.v1.TicketProvider
	17, // 3: ticket.v1.UpdateTicketProviderRequest.update_mask:type_name -> google.protobuf.FieldMask
	18, // 4: ticket.v1.CreateTicketRequest.ticket:type_name -> ticket.v1.Ticket
	18, // 5: ticket.v1.ListTicketsResponse.tickets:type_name -> ticket.v1.Ticket
	18, // 6: ticket.v1.UpdateTicketRequest.ticket:type_name -> ticket.v1.Ticket
	17, // 7: ticket.v1.UpdateTicketRequest.update_mask:type_name -> google.protobuf.FieldMask
	18, // 8: ticket.v1.SyncTicketStatusResponse.ticket:type_name -> ticket.v1.Ticket
	0,  // 9: ticket.v1.TicketService.CreateTicketProvider:input_type -> ticket.v1.CreateTicketProviderRequest
	1,  // 10: ticket.v1.TicketService.GetTicketProvider:input_type -> ticket.v1.GetTicketProviderRequest
	2,  // 11: ticket.v1.TicketService.ListTicketProviders:input_type -> ticket.v1.ListTicketProvidersRequest
	4,  // 12: ticket.v1.TicketService.UpdateTicketProvider:input_type -> ticket.v1.UpdateTicketProviderRequest
	5,  // 13: ticket.v1.TicketService.DeleteTicketProvider:input_type -> ticket.v1.DeleteTicketProviderRequest
	7,  // 14: ticket.v1.TicketService.TestTicketProvider:input_type -> ticket.v1.TestTicketProviderRequest
	9,  // 15: ticket.v1.TicketService.CreateTicket:input_type -> ticket.v1.CreateTicketRequest
	10, // 16: ticket.v1.TicketService.GetTicket:input_type -> ticket.v1.GetTicketRequest
	11, // 17: ticket.v1.TicketService.ListTickets:input_type -> ticket.v1.ListTicketsRequest
	13, // 18: ticket.v1.TicketService.UpdateTicket:input_type -> ticket.v1.UpdateTicketRequest
	14, // 19: ticket.v1.TicketService.SyncTicketStatus:input_type -> ticket.v1.SyncTicketStatusRequest
	16, // 20: ticket.v1.TicketService.CreateTicketProvider:output_type -> ticket.v1.TicketProvider
	16, // 21: ticket.v1.TicketService.GetTicketProvider:output_type -> ticket.v1.TicketProvider
	3,  // 22: ticket.v1.TicketService.ListTicketProviders:output_type -> ticket.v1.ListTicketProvidersResponse
	16, // 23: ticket.v1.TicketService.UpdateTicketProvider:output_type -> ticket.v1.TicketProvider
	6,  // 24: ticket.v1.TicketService.DeleteTicketProvider:output_type -> ticket.v1.DeleteTicketProviderResponse
	8,  // 25: ticket.v1.TicketService.TestTicketProvider:output_type -> ticket.v1.TestTicketProviderResponse
	18, // 26: ticket.v1.TicketService.CreateTicket:output_type -> ticket.v1.Ticket
	18, // 27: ticket.v1.TicketService.GetTicket:output_type -> ticket.v1.Ticket
	12, // 28: ticket.v1.TicketService.ListTickets:output_type -> ticket.v1.ListTicketsResponse
	18, // 29: ticket.v1.TicketService.UpdateTicket:output_type -> ticket.v1.Ticket
	15, // 30: ticket.v1.TicketService.SyncTicketStatus:output_type -> ticket.v1.SyncTicketStatusResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ticket_v1_ticket_service_proto_init() }
func file_ticket_v1_ticket_service_proto_init() {
	if File_ticket_v1_ticket_service_proto != nil {
		return
	}
	file_ticket_v1_ticket_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_v1_ticket_service_proto_rawDesc), len(file_ticket_v1_ticket_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_v1_ticket_service_proto_goTypes,
		DependencyIndexes: file_ticket_v1_ticket_service_proto_depIdxs,
		MessageInfos:      file_ticket_v1_ticket_service_proto_msgTypes,
	}.Build()
	File_ticket_v1_ticket_service_proto = out.File
	file_ticket_v1_ticket_service_proto_goTypes = nil
	file_ticket_v1_ticket_service_proto_depIdxs = nil
}
