// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ticket/v1/ticket.proto

package ticketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProviderType enumerates the supported ticket provider types.
type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	ProviderType_PROVIDER_TYPE_JIRA        ProviderType = 1
	ProviderType_PROVIDER_TYPE_SERVICENOW  ProviderType = 2
	ProviderType_PROVIDER_TYPE_SALESFORCE  ProviderType = 3
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_JIRA",
		2: "PROVIDER_TYPE_SERVICENOW",
		3: "PROVIDER_TYPE_SALESFORCE",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_JIRA":        1,
		"PROVIDER_TYPE_SERVICENOW":  2,
		"PROVIDER_TYPE_SALESFORCE":  3,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_ticket_v1_ticket_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_ticket_v1_ticket_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_proto_rawDescGZIP(), []int{0}
}

// TicketProvider represents a configured external ticketing system provider.
type TicketProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g., "jira", "servicenow", "salesforce"
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"` // Provider-specific configuration
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketProvider) Reset() {
	*x = TicketProvider{}
	mi := &file_ticket_v1_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketProvider) ProtoMessage() {}

func (x *TicketProvider) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketProvider.ProtoReflect.Descriptor instead.
func (*TicketProvider) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *TicketProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketProvider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TicketProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *TicketProvider) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TicketProvider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TicketProvider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TicketProvider) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Ticket represents a ticket synchronized with an external ticketing system.
type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // ID in the external system
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProjectKey    string                 `protobuf:"bytes,4,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"` // e.g., Jira project key
	TicketType    string                 `protobuf:"bytes,5,opt,name=ticket_type,json=ticketType,proto3" json:"ticket_type,omitempty"` // e.g., "incident", "bug", "task"
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,9,opt,name=priority,proto3" json:"priority,omitempty"`
	Assignee      string                 `protobuf:"bytes,10,opt,name=assignee,proto3" json:"assignee,omitempty"`
	AlertId       string                 `protobuf:"bytes,11,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"` // Associated alert ID, if any
	CustomFields  *structpb.Struct       `protobuf:"bytes,12,opt,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SyncedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"` // Last sync with external system
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_ticket_v1_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_v1_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_ticket_v1_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Ticket) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Ticket) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *Ticket) GetTicketType() string {
	if x != nil {
		return x.TicketType
	}
	return ""
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ticket) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ticket) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Ticket) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *Ticket) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Ticket) GetCustomFields() *structpb.Struct {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

func (x *Ticket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ticket) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Ticket) GetSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

var File_ticket_v1_ticket_proto protoreflect.FileDescriptor

const file_ticket_v1_ticket_proto_rawDesc = "" +
	"\n" +
	"\x16ticket/v1/ticket.proto\x12\tticket.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa4\x02\n" +
	"\x0eTicketProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12/\n" +
	"\x06config\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x04\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x1f\n" +
	"\vproject_key\x18\x04 \x01(\tR\n" +
	"projectKey\x12\x1f\n" +
	"\vticket_type\x18\x05 \x01(\tR\n" +
	"ticketType\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\t \x01(\tR\bpriority\x12\x1a\n" +
	"\bassignee\x18\n" +
	" \x01(\tR\bassignee\x12\x19\n" +
	"\balert_id\x18\v \x01(\tR\aalertId\x12<\n" +
	"\rcustom_fields\x18\f \x01(\v2\x17.google.protobuf.StructR\fcustomFields\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tsynced_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt*\x81\x01\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROVIDER_TYPE_JIRA\x10\x01\x12\x1c\n" +
	"\x18PROVIDER_TYPE_SERVICENOW\x10\x02\x12\x1c\n" +
	"\x18PROVIDER_TYPE_SALESFORCE\x10\x03B\xa7\x01\n" +
	"\rcom.ticket.v1B\vTicketProtoP\x01ZDgithub.com/kneutral-org/alerting-system/pkg/proto/ticket/v1;ticketv1\xa2\x02\x03TXX\xaa\x02\tTicket.V1\xca\x02\tTicket\\V1\xe2\x02\x15Ticket\\V1\\GPBMetadata\xea\x02\n" +
	"Ticket::V1b\x06proto3"

var (
	file_ticket_v1_ticket_proto_rawDescOnce sync.Once
	file_ticket_v1_ticket_proto_rawDescData []byte
)

func file_ticket_v1_ticket_proto_rawDescGZIP() []byte {
	file_ticket_v1_ticket_proto_rawDescOnce.Do(func() {
		file_ticket_v1_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_v1_ticket_proto_rawDesc), len(file_ticket_v1_ticket_proto_rawDesc)))
	})
	return file_ticket_v1_ticket_proto_rawDescData
}

var file_ticket_v1_ticket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ticket_v1_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ticket_v1_ticket_proto_goTypes = []any{
	(ProviderType)(0),             // 0: ticket.v1.ProviderType
	(*TicketProvider)(nil),        // 1: ticket.v1.TicketProvider
	(*Ticket)(nil),                // 2: ticket.v1.Ticket
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_ticket_v1_ticket_proto_depIdxs = []int32{
	3, // 0: ticket.v1.TicketProvider.config:type_name -> google.protobuf.Struct
	4, // 1: ticket.v1.TicketProvider.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: ticket.v1.TicketProvider.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: ticket.v1.Ticket.custom_fields:type_name -> google.protobuf.Struct
	4, // 4: ticket.v1.Ticket.created_at:type_name -> google.protobuf.Timestamp
	4, // 5: ticket.v1.Ticket.updated_at:type_name -> google.protobuf.Timestamp
	4, // 6: ticket.v1.Ticket.synced_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ticket_v1_ticket_proto_init() }
func file_ticket_v1_ticket_proto_init() {
	if File_ticket_v1_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_v1_ticket_proto_rawDesc), len(file_ticket_v1_ticket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticket_v1_ticket_proto_goTypes,
		DependencyIndexes: file_ticket_v1_ticket_proto_depIdxs,
		EnumInfos:         file_ticket_v1_ticket_proto_enumTypes,
		MessageInfos:      file_ticket_v1_ticket_proto_msgTypes,
	}.Build()
	File_ticket_v1_ticket_proto = out.File
	file_ticket_v1_ticket_proto_goTypes = nil
	file_ticket_v1_ticket_proto_depIdxs = nil
}
