// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: alerting/v1/alert.proto

package alertingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertStatus int32

const (
	AlertStatus_ALERT_STATUS_UNSPECIFIED  AlertStatus = 0
	AlertStatus_ALERT_STATUS_TRIGGERED    AlertStatus = 1
	AlertStatus_ALERT_STATUS_ACKNOWLEDGED AlertStatus = 2
	AlertStatus_ALERT_STATUS_RESOLVED     AlertStatus = 3
	AlertStatus_ALERT_STATUS_SUPPRESSED   AlertStatus = 4 // During maintenance
)

// Enum value maps for AlertStatus.
var (
	AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_UNSPECIFIED",
		1: "ALERT_STATUS_TRIGGERED",
		2: "ALERT_STATUS_ACKNOWLEDGED",
		3: "ALERT_STATUS_RESOLVED",
		4: "ALERT_STATUS_SUPPRESSED",
	}
	AlertStatus_value = map[string]int32{
		"ALERT_STATUS_UNSPECIFIED":  0,
		"ALERT_STATUS_TRIGGERED":    1,
		"ALERT_STATUS_ACKNOWLEDGED": 2,
		"ALERT_STATUS_RESOLVED":     3,
		"ALERT_STATUS_SUPPRESSED":   4,
	}
)

func (x AlertStatus) Enum() *AlertStatus {
	p := new(AlertStatus)
	*p = x
	return p
}

func (x AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_v1_alert_proto_enumTypes[0].Descriptor()
}

func (AlertStatus) Type() protoreflect.EnumType {
	return &file_alerting_v1_alert_proto_enumTypes[0]
}

func (x AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertStatus.Descriptor instead.
func (AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_alerting_v1_alert_proto_rawDescGZIP(), []int{0}
}

type AlertSource int32

const (
	AlertSource_ALERT_SOURCE_UNSPECIFIED  AlertSource = 0
	AlertSource_ALERT_SOURCE_PROMETHEUS   AlertSource = 1
	AlertSource_ALERT_SOURCE_ALERTMANAGER AlertSource = 2
	AlertSource_ALERT_SOURCE_GRAFANA      AlertSource = 3
	AlertSource_ALERT_SOURCE_GENERIC      AlertSource = 4
	AlertSource_ALERT_SOURCE_MANUAL       AlertSource = 5
)

// Enum value maps for AlertSource.
var (
	AlertSource_name = map[int32]string{
		0: "ALERT_SOURCE_UNSPECIFIED",
		1: "ALERT_SOURCE_PROMETHEUS",
		2: "ALERT_SOURCE_ALERTMANAGER",
		3: "ALERT_SOURCE_GRAFANA",
		4: "ALERT_SOURCE_GENERIC",
		5: "ALERT_SOURCE_MANUAL",
	}
	AlertSource_value = map[string]int32{
		"ALERT_SOURCE_UNSPECIFIED":  0,
		"ALERT_SOURCE_PROMETHEUS":   1,
		"ALERT_SOURCE_ALERTMANAGER": 2,
		"ALERT_SOURCE_GRAFANA":      3,
		"ALERT_SOURCE_GENERIC":      4,
		"ALERT_SOURCE_MANUAL":       5,
	}
)

func (x AlertSource) Enum() *AlertSource {
	p := new(AlertSource)
	*p = x
	return p
}

func (x AlertSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSource) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_v1_alert_proto_enumTypes[1].Descriptor()
}

func (AlertSource) Type() protoreflect.EnumType {
	return &file_alerting_v1_alert_proto_enumTypes[1]
}

func (x AlertSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSource.Descriptor instead.
func (AlertSource) EnumDescriptor() ([]byte, []int) {
	return file_alerting_v1_alert_proto_rawDescGZIP(), []int{1}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_CRITICAL    Severity = 1
	Severity_SEVERITY_HIGH        Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_LOW         Severity = 4
	Severity_SEVERITY_INFO        Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_CRITICAL",
		2: "SEVERITY_HIGH",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_LOW",
		5: "SEVERITY_INFO",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_CRITICAL":    1,
		"SEVERITY_HIGH":        2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_LOW":         4,
		"SEVERITY_INFO":        5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_v1_alert_proto_enumTypes[2].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_alerting_v1_alert_proto_enumTypes[2]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_alerting_v1_alert_proto_rawDescGZIP(), []int{2}
}

type AlertEventType int32

const (
	AlertEventType_ALERT_EVENT_TYPE_UNSPECIFIED  AlertEventType = 0
	AlertEventType_ALERT_EVENT_TYPE_CREATED      AlertEventType = 1
	AlertEventType_ALERT_EVENT_TYPE_ACKNOWLEDGED AlertEventType = 2
	AlertEventType_ALERT_EVENT_TYPE_RESOLVED     AlertEventType = 3
	AlertEventType_ALERT_EVENT_TYPE_ESCALATED    AlertEventType = 4
	AlertEventType_ALERT_EVENT_TYPE_NOTE_ADDED   AlertEventType = 5
	AlertEventType_ALERT_EVENT_TYPE_REASSIGNED   AlertEventType = 6
	AlertEventType_ALERT_EVENT_TYPE_SUPPRESSED   AlertEventType = 7
	AlertEventType_ALERT_EVENT_TYPE_UNSUPPRESSED AlertEventType = 8
)

// Enum value maps for AlertEventType.
var (
	AlertEventType_name = map[int32]string{
		0: "ALERT_EVENT_TYPE_UNSPECIFIED",
		1: "ALERT_EVENT_TYPE_CREATED",
		2: "ALERT_EVENT_TYPE_ACKNOWLEDGED",
		3: "ALERT_EVENT_TYPE_RESOLVED",
		4: "ALERT_EVENT_TYPE_ESCALATED",
		5: "ALERT_EVENT_TYPE_NOTE_ADDED",
		6: "ALERT_EVENT_TYPE_REASSIGNED",
		7: "ALERT_EVENT_TYPE_SUPPRESSED",
		8: "ALERT_EVENT_TYPE_UNSUPPRESSED",
	}
	AlertEventType_value = map[string]int32{
		"ALERT_EVENT_TYPE_UNSPECIFIED":  0,
		"ALERT_EVENT_TYPE_CREATED":      1,
		"ALERT_EVENT_TYPE_ACKNOWLEDGED": 2,
		"ALERT_EVENT_TYPE_RESOLVED":     3,
		"ALERT_EVENT_TYPE_ESCALATED":    4,
		"ALERT_EVENT_TYPE_NOTE_ADDED":   5,
		"ALERT_EVENT_TYPE_REASSIGNED":   6,
		"ALERT_EVENT_TYPE_SUPPRESSED":   7,
		"ALERT_EVENT_TYPE_UNSUPPRESSED": 8,
	}
)

func (x AlertEventType) Enum() *AlertEventType {
	p := new(AlertEventType)
	*p = x
	return p
}

func (x AlertEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_alerting_v1_alert_proto_enumTypes[3].Descriptor()
}

func (AlertEventType) Type() protoreflect.EnumType {
	return &file_alerting_v1_alert_proto_enumTypes[3]
}

func (x AlertEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertEventType.Descriptor instead.
func (AlertEventType) EnumDescriptor() ([]byte, []int) {
	return file_alerting_v1_alert_proto_rawDescGZIP(), []int{3}
}

// Alert represents an alert in the system
type Alert struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fingerprint string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"` // Unique identifier for deduplication
	// Content
	Summary  string   `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Details  string   `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Severity Severity `protobuf:"varint,5,opt,name=severity,proto3,enum=alerting.v1.Severity" json:"severity,omitempty"`
	// Source
	Source         AlertSource `protobuf:"varint,6,opt,name=source,proto3,enum=alerting.v1.AlertSource" json:"source,omitempty"`
	SourceInstance string      `protobuf:"bytes,7,opt,name=source_instance,json=sourceInstance,proto3" json:"source_instance,omitempty"` // e.g., prometheus server name
	// Classification
	ServiceId   string            `protobuf:"bytes,8,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // Service this alert belongs to
	Labels      map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Lifecycle
	Status         AlertStatus            `protobuf:"varint,11,opt,name=status,proto3,enum=alerting.v1.AlertStatus" json:"status,omitempty"`
	TriggeredAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	AcknowledgedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=acknowledged_at,json=acknowledgedAt,proto3" json:"acknowledged_at,omitempty"`
	ResolvedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	// Actors
	AcknowledgedBy string `protobuf:"bytes,15,opt,name=acknowledged_by,json=acknowledgedBy,proto3" json:"acknowledged_by,omitempty"` // User ID
	ResolvedBy     string `protobuf:"bytes,16,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`             // User ID
	EscalatedTo    string `protobuf:"bytes,17,opt,name=escalated_to,json=escalatedTo,proto3" json:"escalated_to,omitempty"`          // Escalation policy ID
	// History
	Notes  []*AlertNote  `protobuf:"bytes,18,rep,name=notes,proto3" json:"notes,omitempty"`
	Events []*AlertEvent `protobuf:"bytes,19,rep,name=events,proto3" json:"events,omitempty"`
	// Metadata
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Webhook payload (original)
	RawPayload    *structpb.Struct `protobuf:"bytes,22,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alerting_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Alert) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Alert) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Alert) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Alert) GetSource() AlertSource {
	if x != nil {
		return x.Source
	}
	return AlertSource_ALERT_SOURCE_UNSPECIFIED
}

func (x *Alert) GetSourceInstance() string {
	if x != nil {
		return x.SourceInstance
	}
	return ""
}

func (x *Alert) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Alert) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Alert) GetStatus() AlertStatus {
	if x != nil {
		return x.Status
	}
	return AlertStatus_ALERT_STATUS_UNSPECIFIED
}

func (x *Alert) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

func (x *Alert) GetAcknowledgedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcknowledgedAt
	}
	return nil
}

func (x *Alert) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *Alert) GetAcknowledgedBy() string {
	if x != nil {
		return x.AcknowledgedBy
	}
	return ""
}

func (x *Alert) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *Alert) GetEscalatedTo() string {
	if x != nil {
		return x.EscalatedTo
	}
	return ""
}

func (x *Alert) GetNotes() []*AlertNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *Alert) GetEvents() []*AlertEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Alert) GetRawPayload() *structpb.Struct {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

type AlertNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // User ID
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertNote) Reset() {
	*x = AlertNote{}
	mi := &file_alerting_v1_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertNote) ProtoMessage() {}

func (x *AlertNote) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertNote.ProtoReflect.Descriptor instead.
func (*AlertNote) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AlertNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertNote) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AlertNote) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AlertNote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AlertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          AlertEventType         `protobuf:"varint,2,opt,name=type,proto3,enum=alerting.v1.AlertEventType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // User ID or system
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEvent) Reset() {
	*x = AlertEvent{}
	mi := &file_alerting_v1_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvent) ProtoMessage() {}

func (x *AlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvent.ProtoReflect.Descriptor instead.
func (*AlertEvent) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_proto_rawDescGZIP(), []int{2}
}

func (x *AlertEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertEvent) GetType() AlertEventType {
	if x != nil {
		return x.Type
	}
	return AlertEventType_ALERT_EVENT_TYPE_UNSPECIFIED
}

func (x *AlertEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AlertEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AlertEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_alerting_v1_alert_proto protoreflect.FileDescriptor

const file_alerting_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x17alerting/v1/alert.proto\x12\valerting.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x83\t\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x121\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x15.alerting.v1.SeverityR\bseverity\x120\n" +
	"\x06source\x18\x06 \x01(\x0e2\x18.alerting.v1.AlertSourceR\x06source\x12'\n" +
	"\x0fsource_instance\x18\a \x01(\tR\x0esourceInstance\x12\x1d\n" +
	"\n" +
	"service_id\x18\b \x01(\tR\tserviceId\x126\n" +
	"\x06labels\x18\t \x03(\v2\x1e.alerting.v1.Alert.LabelsEntryR\x06labels\x12E\n" +
	"\vannotations\x18\n" +
	" \x03(\v2#.alerting.v1.Alert.AnnotationsEntryR\vannotations\x120\n" +
	"\x06status\x18\v \x01(\x0e2\x18.alerting.v1.AlertStatusR\x06status\x12=\n" +
	"\ftriggered_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\x12C\n" +
	"\x0facknowledged_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0eacknowledgedAt\x12;\n" +
	"\vresolved_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x12'\n" +
	"\x0facknowledged_by\x18\x0f \x01(\tR\x0eacknowledgedBy\x12\x1f\n" +
	"\vresolved_by\x18\x10 \x01(\tR\n" +
	"resolvedBy\x12!\n" +
	"\fescalated_to\x18\x11 \x01(\tR\vescalatedTo\x12,\n" +
	"\x05notes\x18\x12 \x03(\v2\x16.alerting.v1.AlertNoteR\x05notes\x12/\n" +
	"\x06events\x18\x13 \x03(\v2\x17.alerting.v1.AlertEventR\x06events\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\vraw_payload\x18\x16 \x01(\v2\x17.google.protobuf.StructR\n" +
	"rawPayload\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\tAlertNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc4\x02\n" +
	"\n" +
	"AlertEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.alerting.v1.AlertEventTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.alerting.v1.AlertEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x9e\x01\n" +
	"\vAlertStatus\x12\x1c\n" +
	"\x18ALERT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALERT_STATUS_TRIGGERED\x10\x01\x12\x1d\n" +
	"\x19ALERT_STATUS_ACKNOWLEDGED\x10\x02\x12\x19\n" +
	"\x15ALERT_STATUS_RESOLVED\x10\x03\x12\x1b\n" +
	"\x17ALERT_STATUS_SUPPRESSED\x10\x04*\xb4\x01\n" +
	"\vAlertSource\x12\x1c\n" +
	"\x18ALERT_SOURCE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ALERT_SOURCE_PROMETHEUS\x10\x01\x12\x1d\n" +
	"\x19ALERT_SOURCE_ALERTMANAGER\x10\x02\x12\x18\n" +
	"\x14ALERT_SOURCE_GRAFANA\x10\x03\x12\x18\n" +
	"\x14ALERT_SOURCE_GENERIC\x10\x04\x12\x17\n" +
	"\x13ALERT_SOURCE_MANUAL\x10\x05*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x01\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x04\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x05*\xb8\x02\n" +
	"\x0eAlertEventType\x12 \n" +
	"\x1cALERT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ALERT_EVENT_TYPE_CREATED\x10\x01\x12!\n" +
	"\x1dALERT_EVENT_TYPE_ACKNOWLEDGED\x10\x02\x12\x1d\n" +
	"\x19ALERT_EVENT_TYPE_RESOLVED\x10\x03\x12\x1e\n" +
	"\x1aALERT_EVENT_TYPE_ESCALATED\x10\x04\x12\x1f\n" +
	"\x1bALERT_EVENT_TYPE_NOTE_ADDED\x10\x05\x12\x1f\n" +
	"\x1bALERT_EVENT_TYPE_REASSIGNED\x10\x06\x12\x1f\n" +
	"\x1bALERT_EVENT_TYPE_SUPPRESSED\x10\a\x12!\n" +
	"\x1dALERT_EVENT_TYPE_UNSUPPRESSED\x10\bB\xb4\x01\n" +
	"\x0fcom.alerting.v1B\n" +
	"AlertProtoP\x01ZHgithub.com/kneutral-org/alerting-system/pkg/proto/alerting/v1;alertingv1\xa2\x02\x03AXX\xaa\x02\vAlerting.V1\xca\x02\vAlerting\\V1\xe2\x02\x17Alerting\\V1\\GPBMetadata\xea\x02\fAlerting::V1b\x06proto3"

var (
	file_alerting_v1_alert_proto_rawDescOnce sync.Once
	file_alerting_v1_alert_proto_rawDescData []byte
)

func file_alerting_v1_alert_proto_rawDescGZIP() []byte {
	file_alerting_v1_alert_proto_rawDescOnce.Do(func() {
		file_alerting_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerting_v1_alert_proto_rawDesc), len(file_alerting_v1_alert_proto_rawDesc)))
	})
	return file_alerting_v1_alert_proto_rawDescData
}

var file_alerting_v1_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_alerting_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_alerting_v1_alert_proto_goTypes = []any{
	(AlertStatus)(0),              // 0: alerting.v1.AlertStatus
	(AlertSource)(0),              // 1: alerting.v1.AlertSource
	(Severity)(0),                 // 2: alerting.v1.Severity
	(AlertEventType)(0),           // 3: alerting.v1.AlertEventType
	(*Alert)(nil),                 // 4: alerting.v1.Alert
	(*AlertNote)(nil),             // 5: alerting.v1.AlertNote
	(*AlertEvent)(nil),            // 6: alerting.v1.AlertEvent
	nil,                           // 7: alerting.v1.Alert.LabelsEntry
	nil,                           // 8: alerting.v1.Alert.AnnotationsEntry
	nil,                           // 9: alerting.v1.AlertEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 11: google.protobuf.Struct
}
var file_alerting_v1_alert_proto_depIdxs = []int32{
	2,  // 0: alerting.v1.Alert.severity:type_name -> alerting.v1.Severity
	1,  // 1: alerting.v1.Alert.source:type_name -> alerting.v1.AlertSource
	7,  // 2: alerting.v1.Alert.labels:type_name -> alerting.v1.Alert.LabelsEntry
	8,  // 3: alerting.v1.Alert.annotations:type_name -> alerting.v1.Alert.AnnotationsEntry
	0,  // 4: alerting.v1.Alert.status:type_name -> alerting.v1.AlertStatus
	10, // 5: alerting.v1.Alert.triggered_at:type_name -> google.protobuf.Timestamp
	10, // 6: alerting.v1.Alert.acknowledged_at:type_name -> google.protobuf.Timestamp
	10, // 7: alerting.v1.Alert.resolved_at:type_name -> google.protobuf.Timestamp
	5,  // 8: alerting.v1.Alert.notes:type_name -> alerting.v1.AlertNote
	6,  // 9: alerting.v1.Alert.events:type_name -> alerting.v1.AlertEvent
	10, // 10: alerting.v1.Alert.created_at:type_name -> google.protobuf.Timestamp
	10, // 11: alerting.v1.Alert.updated_at:type_name -> google.protobuf.Timestamp
	11, // 12: alerting.v1.Alert.raw_payload:type_name -> google.protobuf.Struct
	10, // 13: alerting.v1.AlertNote.created_at:type_name -> google.protobuf.Timestamp
	3,  // 14: alerting.v1.AlertEvent.type:type_name -> alerting.v1.AlertEventType
	10, // 15: alerting.v1.AlertEvent.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 16: alerting.v1.AlertEvent.metadata:type_name -> alerting.v1.AlertEvent.MetadataEntry
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_alerting_v1_alert_proto_init() }
func file_alerting_v1_alert_proto_init() {
	if File_alerting_v1_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerting_v1_alert_proto_rawDesc), len(file_alerting_v1_alert_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alerting_v1_alert_proto_goTypes,
		DependencyIndexes: file_alerting_v1_alert_proto_depIdxs,
		EnumInfos:         file_alerting_v1_alert_proto_enumTypes,
		MessageInfos:      file_alerting_v1_alert_proto_msgTypes,
	}.Build()
	File_alerting_v1_alert_proto = out.File
	file_alerting_v1_alert_proto_goTypes = nil
	file_alerting_v1_alert_proto_depIdxs = nil
}
