// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: alerting/v1/alert_service.proto

package alertingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAlertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For Alertmanager/Prometheus format
	Summary     string            `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Details     string            `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	Severity    Severity          `protobuf:"varint,3,opt,name=severity,proto3,enum=alerting.v1.Severity" json:"severity,omitempty"`
	Source      AlertSource       `protobuf:"varint,4,opt,name=source,proto3,enum=alerting.v1.AlertSource" json:"source,omitempty"`
	ServiceId   string            `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Labels      map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Raw webhook payload for generic sources
	RawPayload *structpb.Struct `protobuf:"bytes,8,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	// Optional fingerprint (auto-generated if not provided)
	Fingerprint   string `protobuf:"bytes,9,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRequest) Reset() {
	*x = CreateAlertRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRequest) ProtoMessage() {}

func (x *CreateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlertRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateAlertRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *CreateAlertRequest) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *CreateAlertRequest) GetSource() AlertSource {
	if x != nil {
		return x.Source
	}
	return AlertSource_ALERT_SOURCE_UNSPECIFIED
}

func (x *CreateAlertRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateAlertRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateAlertRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *CreateAlertRequest) GetRawPayload() *structpb.Struct {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *CreateAlertRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAlertsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filters
	Statuses       []AlertStatus     `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=alerting.v1.AlertStatus" json:"statuses,omitempty"`
	Severities     []Severity        `protobuf:"varint,4,rep,packed,name=severities,proto3,enum=alerting.v1.Severity" json:"severities,omitempty"`
	Sources        []AlertSource     `protobuf:"varint,5,rep,packed,name=sources,proto3,enum=alerting.v1.AlertSource" json:"sources,omitempty"`
	ServiceId      string            `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	LabelSelectors map[string]string `protobuf:"bytes,7,rep,name=label_selectors,json=labelSelectors,proto3" json:"label_selectors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key=value matchers
	// Time range
	TriggeredAfter  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=triggered_after,json=triggeredAfter,proto3" json:"triggered_after,omitempty"`
	TriggeredBefore *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=triggered_before,json=triggeredBefore,proto3" json:"triggered_before,omitempty"`
	// Search
	SearchQuery string `protobuf:"bytes,10,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // Full-text search in summary/details
	// Sorting
	OrderBy       string `protobuf:"bytes,11,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // e.g., "triggered_at desc", "severity asc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListAlertsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAlertsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAlertsRequest) GetStatuses() []AlertStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListAlertsRequest) GetSeverities() []Severity {
	if x != nil {
		return x.Severities
	}
	return nil
}

func (x *ListAlertsRequest) GetSources() []AlertSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListAlertsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListAlertsRequest) GetLabelSelectors() map[string]string {
	if x != nil {
		return x.LabelSelectors
	}
	return nil
}

func (x *ListAlertsRequest) GetTriggeredAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAfter
	}
	return nil
}

func (x *ListAlertsRequest) GetTriggeredBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredBefore
	}
	return nil
}

func (x *ListAlertsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListAlertsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *ListAlertsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAlertsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRequest) Reset() {
	*x = UpdateAlertRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRequest) ProtoMessage() {}

func (x *UpdateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAlertRequest) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *UpdateAlertRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type AcknowledgeAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"` // Optional acknowledgment note
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeAlertRequest) Reset() {
	*x = AcknowledgeAlertRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertRequest) ProtoMessage() {}

func (x *AcknowledgeAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{5}
}

func (x *AcknowledgeAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcknowledgeAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcknowledgeAlertRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ResolveAlertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResolutionNote string                 `protobuf:"bytes,3,opt,name=resolution_note,json=resolutionNote,proto3" json:"resolution_note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveAlertRequest) Reset() {
	*x = ResolveAlertRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAlertRequest) ProtoMessage() {}

func (x *ResolveAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAlertRequest.ProtoReflect.Descriptor instead.
func (*ResolveAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResolveAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolveAlertRequest) GetResolutionNote() string {
	if x != nil {
		return x.ResolutionNote
	}
	return ""
}

type EscalateAlertRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EscalationPolicyId string                 `protobuf:"bytes,2,opt,name=escalation_policy_id,json=escalationPolicyId,proto3" json:"escalation_policy_id,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                               // Who initiated escalation
	SkipCurrentStep    bool                   `protobuf:"varint,4,opt,name=skip_current_step,json=skipCurrentStep,proto3" json:"skip_current_step,omitempty"` // Skip to next escalation step
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EscalateAlertRequest) Reset() {
	*x = EscalateAlertRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscalateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalateAlertRequest) ProtoMessage() {}

func (x *EscalateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalateAlertRequest.ProtoReflect.Descriptor instead.
func (*EscalateAlertRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{7}
}

func (x *EscalateAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EscalateAlertRequest) GetEscalationPolicyId() string {
	if x != nil {
		return x.EscalationPolicyId
	}
	return ""
}

func (x *EscalateAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EscalateAlertRequest) GetSkipCurrentStep() bool {
	if x != nil {
		return x.SkipCurrentStep
	}
	return false
}

type AddNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNoteRequest) Reset() {
	*x = AddNoteRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNoteRequest) ProtoMessage() {}

func (x *AddNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNoteRequest.ProtoReflect.Descriptor instead.
func (*AddNoteRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddNoteRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AddNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddNoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAlertEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertEventsRequest) Reset() {
	*x = GetAlertEventsRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertEventsRequest) ProtoMessage() {}

func (x *GetAlertEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertEventsRequest.ProtoReflect.Descriptor instead.
func (*GetAlertEventsRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAlertEventsRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *GetAlertEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAlertEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetAlertEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AlertEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertEventsResponse) Reset() {
	*x = GetAlertEventsResponse{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertEventsResponse) ProtoMessage() {}

func (x *GetAlertEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertEventsResponse.ProtoReflect.Descriptor instead.
func (*GetAlertEventsResponse) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAlertEventsResponse) GetEvents() []*AlertEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetAlertEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BulkAcknowledgeAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertIds      []string               `protobuf:"bytes,1,rep,name=alert_ids,json=alertIds,proto3" json:"alert_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkAcknowledgeAlertsRequest) Reset() {
	*x = BulkAcknowledgeAlertsRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkAcknowledgeAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkAcknowledgeAlertsRequest) ProtoMessage() {}

func (x *BulkAcknowledgeAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkAcknowledgeAlertsRequest.ProtoReflect.Descriptor instead.
func (*BulkAcknowledgeAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{11}
}

func (x *BulkAcknowledgeAlertsRequest) GetAlertIds() []string {
	if x != nil {
		return x.AlertIds
	}
	return nil
}

func (x *BulkAcknowledgeAlertsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BulkAcknowledgeAlertsRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type BulkAcknowledgeAlertsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AcknowledgedCount int32                  `protobuf:"varint,1,opt,name=acknowledged_count,json=acknowledgedCount,proto3" json:"acknowledged_count,omitempty"`
	FailedIds         []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	FailureReasons    []string               `protobuf:"bytes,3,rep,name=failure_reasons,json=failureReasons,proto3" json:"failure_reasons,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BulkAcknowledgeAlertsResponse) Reset() {
	*x = BulkAcknowledgeAlertsResponse{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkAcknowledgeAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkAcknowledgeAlertsResponse) ProtoMessage() {}

func (x *BulkAcknowledgeAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkAcknowledgeAlertsResponse.ProtoReflect.Descriptor instead.
func (*BulkAcknowledgeAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{12}
}

func (x *BulkAcknowledgeAlertsResponse) GetAcknowledgedCount() int32 {
	if x != nil {
		return x.AcknowledgedCount
	}
	return 0
}

func (x *BulkAcknowledgeAlertsResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

func (x *BulkAcknowledgeAlertsResponse) GetFailureReasons() []string {
	if x != nil {
		return x.FailureReasons
	}
	return nil
}

type BulkResolveAlertsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlertIds       []string               `protobuf:"bytes,1,rep,name=alert_ids,json=alertIds,proto3" json:"alert_ids,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResolutionNote string                 `protobuf:"bytes,3,opt,name=resolution_note,json=resolutionNote,proto3" json:"resolution_note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BulkResolveAlertsRequest) Reset() {
	*x = BulkResolveAlertsRequest{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResolveAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResolveAlertsRequest) ProtoMessage() {}

func (x *BulkResolveAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResolveAlertsRequest.ProtoReflect.Descriptor instead.
func (*BulkResolveAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{13}
}

func (x *BulkResolveAlertsRequest) GetAlertIds() []string {
	if x != nil {
		return x.AlertIds
	}
	return nil
}

func (x *BulkResolveAlertsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BulkResolveAlertsRequest) GetResolutionNote() string {
	if x != nil {
		return x.ResolutionNote
	}
	return ""
}

type BulkResolveAlertsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResolvedCount  int32                  `protobuf:"varint,1,opt,name=resolved_count,json=resolvedCount,proto3" json:"resolved_count,omitempty"`
	FailedIds      []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	FailureReasons []string               `protobuf:"bytes,3,rep,name=failure_reasons,json=failureReasons,proto3" json:"failure_reasons,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BulkResolveAlertsResponse) Reset() {
	*x = BulkResolveAlertsResponse{}
	mi := &file_alerting_v1_alert_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResolveAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResolveAlertsResponse) ProtoMessage() {}

func (x *BulkResolveAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerting_v1_alert_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResolveAlertsResponse.ProtoReflect.Descriptor instead.
func (*BulkResolveAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alerting_v1_alert_service_proto_rawDescGZIP(), []int{14}
}

func (x *BulkResolveAlertsResponse) GetResolvedCount() int32 {
	if x != nil {
		return x.ResolvedCount
	}
	return 0
}

func (x *BulkResolveAlertsResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

func (x *BulkResolveAlertsResponse) GetFailureReasons() []string {
	if x != nil {
		return x.FailureReasons
	}
	return nil
}

var File_alerting_v1_alert_service_proto protoreflect.FileDescriptor

const file_alerting_v1_alert_service_proto_rawDesc = "" +
	"\n" +
	"\x1falerting/v1/alert_service.proto\x12\valerting.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17alerting/v1/alert.proto\"\xbc\x04\n" +
	"\x12CreateAlertRequest\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\x121\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x15.alerting.v1.SeverityR\bseverity\x120\n" +
	"\x06source\x18\x04 \x01(\x0e2\x18.alerting.v1.AlertSourceR\x06source\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x12C\n" +
	"\x06labels\x18\x06 \x03(\v2+.alerting.v1.CreateAlertRequest.LabelsEntryR\x06labels\x12R\n" +
	"\vannotations\x18\a \x03(\v20.alerting.v1.CreateAlertRequest.AnnotationsEntryR\vannotations\x128\n" +
	"\vraw_payload\x18\b \x01(\v2\x17.google.protobuf.StructR\n" +
	"rawPayload\x12 \n" +
	"\vfingerprint\x18\t \x01(\tR\vfingerprint\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf9\x04\n" +
	"\x11ListAlertsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x124\n" +
	"\bstatuses\x18\x03 \x03(\x0e2\x18.alerting.v1.AlertStatusR\bstatuses\x125\n" +
	"\n" +
	"severities\x18\x04 \x03(\x0e2\x15.alerting.v1.SeverityR\n" +
	"severities\x122\n" +
	"\asources\x18\x05 \x03(\x0e2\x18.alerting.v1.AlertSourceR\asources\x12\x1d\n" +
	"\n" +
	"service_id\x18\x06 \x01(\tR\tserviceId\x12[\n" +
	"\x0flabel_selectors\x18\a \x03(\v22.alerting.v1.ListAlertsRequest.LabelSelectorsEntryR\x0elabelSelectors\x12C\n" +
	"\x0ftriggered_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0etriggeredAfter\x12E\n" +
	"\x10triggered_before\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0ftriggeredBefore\x12!\n" +
	"\fsearch_query\x18\n" +
	" \x01(\tR\vsearchQuery\x12\x19\n" +
	"\border_by\x18\v \x01(\tR\aorderBy\x1aA\n" +
	"\x13LabelSelectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x12ListAlertsResponse\x12*\n" +
	"\x06alerts\x18\x01 \x03(\v2\x12.alerting.v1.AlertR\x06alerts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"{\n" +
	"\x12UpdateAlertRequest\x12(\n" +
	"\x05alert\x18\x01 \x01(\v2\x12.alerting.v1.AlertR\x05alert\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"V\n" +
	"\x17AcknowledgeAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"g\n" +
	"\x13ResolveAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fresolution_note\x18\x03 \x01(\tR\x0eresolutionNote\"\x9d\x01\n" +
	"\x14EscalateAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14escalation_policy_id\x18\x02 \x01(\tR\x12escalationPolicyId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12*\n" +
	"\x11skip_current_step\x18\x04 \x01(\bR\x0fskipCurrentStep\"^\n" +
	"\x0eAddNoteRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"n\n" +
	"\x15GetAlertEventsRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"q\n" +
	"\x16GetAlertEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.alerting.v1.AlertEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"h\n" +
	"\x1cBulkAcknowledgeAlertsRequest\x12\x1b\n" +
	"\talert_ids\x18\x01 \x03(\tR\balertIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"\x96\x01\n" +
	"\x1dBulkAcknowledgeAlertsResponse\x12-\n" +
	"\x12acknowledged_count\x18\x01 \x01(\x05R\x11acknowledgedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\x12'\n" +
	"\x0ffailure_reasons\x18\x03 \x03(\tR\x0efailureReasons\"y\n" +
	"\x18BulkResolveAlertsRequest\x12\x1b\n" +
	"\talert_ids\x18\x01 \x03(\tR\balertIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fresolution_note\x18\x03 \x01(\tR\x0eresolutionNote\"\x8a\x01\n" +
	"\x19BulkResolveAlertsResponse\x12%\n" +
	"\x0eresolved_count\x18\x01 \x01(\x05R\rresolvedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\x12'\n" +
	"\x0ffailure_reasons\x18\x03 \x03(\tR\x0efailureReasons2\xea\x06\n" +
	"\fAlertService\x12B\n" +
	"\vCreateAlert\x12\x1f.alerting.v1.CreateAlertRequest\x1a\x12.alerting.v1.Alert\x12<\n" +
	"\bGetAlert\x12\x1c.alerting.v1.GetAlertRequest\x1a\x12.alerting.v1.Alert\x12M\n" +
	"\n" +
	"ListAlerts\x12\x1e.alerting.v1.ListAlertsRequest\x1a\x1f.alerting.v1.ListAlertsResponse\x12B\n" +
	"\vUpdateAlert\x12\x1f.alerting.v1.UpdateAlertRequest\x1a\x12.alerting.v1.Alert\x12L\n" +
	"\x10AcknowledgeAlert\x12$.alerting.v1.AcknowledgeAlertRequest\x1a\x12.alerting.v1.Alert\x12D\n" +
	"\fResolveAlert\x12 .alerting.v1.ResolveAlertRequest\x1a\x12.alerting.v1.Alert\x12F\n" +
	"\rEscalateAlert\x12!.alerting.v1.EscalateAlertRequest\x1a\x12.alerting.v1.Alert\x12:\n" +
	"\aAddNote\x12\x1b.alerting.v1.AddNoteRequest\x1a\x12.alerting.v1.Alert\x12Y\n" +
	"\x0eGetAlertEvents\x12\".alerting.v1.GetAlertEventsRequest\x1a#.alerting.v1.GetAlertEventsResponse\x12n\n" +
	"\x15BulkAcknowledgeAlerts\x12).alerting.v1.BulkAcknowledgeAlertsRequest\x1a*.alerting.v1.BulkAcknowledgeAlertsResponse\x12b\n" +
	"\x11BulkResolveAlerts\x12%.alerting.v1.BulkResolveAlertsRequest\x1a&.alerting.v1.BulkResolveAlertsResponseB\xbb\x01\n" +
	"\x0fcom.alerting.v1B\x11AlertServiceProtoP\x01ZHgithub.com/kneutral-org/alerting-system/pkg/proto/alerting/v1;alertingv1\xa2\x02\x03AXX\xaa\x02\vAlerting.V1\xca\x02\vAlerting\\V1\xe2\x02\x17Alerting\\V1\\GPBMetadata\xea\x02\fAlerting::V1b\x06proto3"

var (
	file_alerting_v1_alert_service_proto_rawDescOnce sync.Once
	file_alerting_v1_alert_service_proto_rawDescData []byte
)

func file_alerting_v1_alert_service_proto_rawDescGZIP() []byte {
	file_alerting_v1_alert_service_proto_rawDescOnce.Do(func() {
		file_alerting_v1_alert_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerting_v1_alert_service_proto_rawDesc), len(file_alerting_v1_alert_service_proto_rawDesc)))
	})
	return file_alerting_v1_alert_service_proto_rawDescData
}

var file_alerting_v1_alert_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_alerting_v1_alert_service_proto_goTypes = []any{
	(*CreateAlertRequest)(nil),            // 0: alerting.v1.CreateAlertRequest
	(*GetAlertRequest)(nil),               // 1: alerting.v1.GetAlertRequest
	(*ListAlertsRequest)(nil),             // 2: alerting.v1.ListAlertsRequest
	(*ListAlertsResponse)(nil),            // 3: alerting.v1.ListAlertsResponse
	(*UpdateAlertRequest)(nil),            // 4: alerting.v1.UpdateAlertRequest
	(*AcknowledgeAlertRequest)(nil),       // 5: alerting.v1.AcknowledgeAlertRequest
	(*ResolveAlertRequest)(nil),           // 6: alerting.v1.ResolveAlertRequest
	(*EscalateAlertRequest)(nil),          // 7: alerting.v1.EscalateAlertRequest
	(*AddNoteRequest)(nil),                // 8: alerting.v1.AddNoteRequest
	(*GetAlertEventsRequest)(nil),         // 9: alerting.v1.GetAlertEventsRequest
	(*GetAlertEventsResponse)(nil),        // 10: alerting.v1.GetAlertEventsResponse
	(*BulkAcknowledgeAlertsRequest)(nil),  // 11: alerting.v1.BulkAcknowledgeAlertsRequest
	(*BulkAcknowledgeAlertsResponse)(nil), // 12: alerting.v1.BulkAcknowledgeAlertsResponse
	(*BulkResolveAlertsRequest)(nil),      // 13: alerting.v1.BulkResolveAlertsRequest
	(*BulkResolveAlertsResponse)(nil),     // 14: alerting.v1.BulkResolveAlertsResponse
	nil,                                   // 15: alerting.v1.CreateAlertRequest.LabelsEntry
	nil,                                   // 16: alerting.v1.CreateAlertRequest.AnnotationsEntry
	nil,                                   // 17: alerting.v1.ListAlertsRequest.LabelSelectorsEntry
	(Severity)(0),                         // 18: alerting.v1.Severity
	(AlertSource)(0),                      // 19: alerting.v1.AlertSource
	(*structpb.Struct)(nil),               // 20: google.protobuf.Struct
	(AlertStatus)(0),                      // 21: alerting.v1.AlertStatus
	(*timestamppb.Timestamp)(nil),         // 22: google.protobuf.Timestamp
	(*Alert)(nil),                         // 23: alerting.v1.Alert
	(*fieldmaskpb.FieldMask)(nil),         // 24: google.protobuf.FieldMask
	(*AlertEvent)(nil),                    // 25: alerting.v1.AlertEvent
}
var file_alerting_v1_alert_service_proto_depIdxs = []int32{
	18, // 0: alerting.v1.CreateAlertRequest.severity:type_name -> alerting.v1.Severity
	19, // 1: alerting.v1.CreateAlertRequest.source:type_name -> alerting.v1.AlertSource
	15, // 2: alerting.v1.CreateAlertRequest.labels:type_name -> alerting.v1.CreateAlertRequest.LabelsEntry
	16, // 3: alerting.v1.CreateAlertRequest.annotations:type_name -> alerting.v1.CreateAlertRequest.AnnotationsEntry
	20, // 4: alerting.v1.CreateAlertRequest.raw_payload:type_name -> google.protobuf.Struct
	21, // 5: alerting.v1.ListAlertsRequest.statuses:type_name -> alerting.v1.AlertStatus
	18, // 6: alerting.v1.ListAlertsRequest.severities:type_name -> alerting.v1.Severity
	19, // 7: alerting.v1.ListAlertsRequest.sources:type_name -> alerting.v1.AlertSource
	17, // 8: alerting.v1.ListAlertsRequest.label_selectors:type_name -> alerting.v1.ListAlertsRequest.LabelSelectorsEntry
	22, // 9: alerting.v1.ListAlertsRequest.triggered_after:type_name -> google.protobuf.Timestamp
	22, // 10: alerting.v1.ListAlertsRequest.triggered_before:type_name -> google.protobuf.Timestamp
	23, // 11: alerting.v1.ListAlertsResponse.alerts:type_name -> alerting.v1.Alert
	23, // 12: alerting.v1.UpdateAlertRequest.alert:type_name -> alerting.v1.Alert
	24, // 13: alerting.v1.UpdateAlertRequest.update_mask:type_name -> google.protobuf.FieldMask
	25, // 14: alerting.v1.GetAlertEventsResponse.events:type_name -> alerting.v1.AlertEvent
	0,  // 15: alerting.v1.AlertService.CreateAlert:input_type -> alerting.v1.CreateAlertRequest
	1,  // 16: alerting.v1.AlertService.GetAlert:input_type -> alerting.v1.GetAlertRequest
	2,  // 17: alerting.v1.AlertService.ListAlerts:input_type -> alerting.v1.ListAlertsRequest
	4,  // 18: alerting.v1.AlertService.UpdateAlert:input_type -> alerting.v1.UpdateAlertRequest
	5,  // 19: alerting.v1.AlertService.AcknowledgeAlert:input_type -> alerting.v1.AcknowledgeAlertRequest
	6,  // 20: alerting.v1.AlertService.ResolveAlert:input_type -> alerting.v1.ResolveAlertRequest
	7,  // 21: alerting.v1.AlertService.EscalateAlert:input_type -> alerting.v1.EscalateAlertRequest
	8,  // 22: alerting.v1.AlertService.AddNote:input_type -> alerting.v1.AddNoteRequest
	9,  // 23: alerting.v1.AlertService.GetAlertEvents:input_type -> alerting.v1.GetAlertEventsRequest
	11, // 24: alerting.v1.AlertService.BulkAcknowledgeAlerts:input_type -> alerting.v1.BulkAcknowledgeAlertsRequest
	13, // 25: alerting.v1.AlertService.BulkResolveAlerts:input_type -> alerting.v1.BulkResolveAlertsRequest
	23, // 26: alerting.v1.AlertService.CreateAlert:output_type -> alerting.v1.Alert
	23, // 27: alerting.v1.AlertService.GetAlert:output_type -> alerting.v1.Alert
	3,  // 28: alerting.v1.AlertService.ListAlerts:output_type -> alerting.v1.ListAlertsResponse
	23, // 29: alerting.v1.AlertService.UpdateAlert:output_type -> alerting.v1.Alert
	23, // 30: alerting.v1.AlertService.AcknowledgeAlert:output_type -> alerting.v1.Alert
	23, // 31: alerting.v1.AlertService.ResolveAlert:output_type -> alerting.v1.Alert
	23, // 32: alerting.v1.AlertService.EscalateAlert:output_type -> alerting.v1.Alert
	23, // 33: alerting.v1.AlertService.AddNote:output_type -> alerting.v1.Alert
	10, // 34: alerting.v1.AlertService.GetAlertEvents:output_type -> alerting.v1.GetAlertEventsResponse
	12, // 35: alerting.v1.AlertService.BulkAcknowledgeAlerts:output_type -> alerting.v1.BulkAcknowledgeAlertsResponse
	14, // 36: alerting.v1.AlertService.BulkResolveAlerts:output_type -> alerting.v1.BulkResolveAlertsResponse
	26, // [26:37] is the sub-list for method output_type
	15, // [15:26] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_alerting_v1_alert_service_proto_init() }
func file_alerting_v1_alert_service_proto_init() {
	if File_alerting_v1_alert_service_proto != nil {
		return
	}
	file_alerting_v1_alert_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerting_v1_alert_service_proto_rawDesc), len(file_alerting_v1_alert_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alerting_v1_alert_service_proto_goTypes,
		DependencyIndexes: file_alerting_v1_alert_service_proto_depIdxs,
		MessageInfos:      file_alerting_v1_alert_service_proto_msgTypes,
	}.Build()
	File_alerting_v1_alert_service_proto = out.File
	file_alerting_v1_alert_service_proto_goTypes = nil
	file_alerting_v1_alert_service_proto_depIdxs = nil
}
