// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: alerting/v1/alert_service.proto

package alertingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertService_CreateAlert_FullMethodName           = "/alerting.v1.AlertService/CreateAlert"
	AlertService_GetAlert_FullMethodName              = "/alerting.v1.AlertService/GetAlert"
	AlertService_ListAlerts_FullMethodName            = "/alerting.v1.AlertService/ListAlerts"
	AlertService_UpdateAlert_FullMethodName           = "/alerting.v1.AlertService/UpdateAlert"
	AlertService_AcknowledgeAlert_FullMethodName      = "/alerting.v1.AlertService/AcknowledgeAlert"
	AlertService_ResolveAlert_FullMethodName          = "/alerting.v1.AlertService/ResolveAlert"
	AlertService_EscalateAlert_FullMethodName         = "/alerting.v1.AlertService/EscalateAlert"
	AlertService_AddNote_FullMethodName               = "/alerting.v1.AlertService/AddNote"
	AlertService_GetAlertEvents_FullMethodName        = "/alerting.v1.AlertService/GetAlertEvents"
	AlertService_BulkAcknowledgeAlerts_FullMethodName = "/alerting.v1.AlertService/BulkAcknowledgeAlerts"
	AlertService_BulkResolveAlerts_FullMethodName     = "/alerting.v1.AlertService/BulkResolveAlerts"
)

// AlertServiceClient is the client API for AlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AlertService provides alert management operations
type AlertServiceClient interface {
	// Create a new alert (typically from webhook)
	CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// Get alert by ID
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// List alerts with filters
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	// Update alert (limited fields)
	UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// Acknowledge an alert
	AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// Resolve an alert
	ResolveAlert(ctx context.Context, in *ResolveAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// Escalate alert to policy
	EscalateAlert(ctx context.Context, in *EscalateAlertRequest, opts ...grpc.CallOption) (*Alert, error)
	// Add note to alert
	AddNote(ctx context.Context, in *AddNoteRequest, opts ...grpc.CallOption) (*Alert, error)
	// Get alert events/history
	GetAlertEvents(ctx context.Context, in *GetAlertEventsRequest, opts ...grpc.CallOption) (*GetAlertEventsResponse, error)
	// Bulk acknowledge alerts
	BulkAcknowledgeAlerts(ctx context.Context, in *BulkAcknowledgeAlertsRequest, opts ...grpc.CallOption) (*BulkAcknowledgeAlertsResponse, error)
	// Bulk resolve alerts
	BulkResolveAlerts(ctx context.Context, in *BulkResolveAlertsRequest, opts ...grpc.CallOption) (*BulkResolveAlertsResponse, error)
}

type alertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertServiceClient(cc grpc.ClientConnInterface) AlertServiceClient {
	return &alertServiceClient{cc}
}

func (c *alertServiceClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertService_CreateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertService_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, AlertService_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertService_UpdateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertService_AcknowledgeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) ResolveAlert(ctx context.Context, in *ResolveAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertService_ResolveAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) EscalateAlert(ctx context.Context, in *EscalateAlertRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertService_EscalateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) AddNote(ctx context.Context, in *AddNoteRequest, opts ...grpc.CallOption) (*Alert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Alert)
	err := c.cc.Invoke(ctx, AlertService_AddNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) GetAlertEvents(ctx context.Context, in *GetAlertEventsRequest, opts ...grpc.CallOption) (*GetAlertEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertEventsResponse)
	err := c.cc.Invoke(ctx, AlertService_GetAlertEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) BulkAcknowledgeAlerts(ctx context.Context, in *BulkAcknowledgeAlertsRequest, opts ...grpc.CallOption) (*BulkAcknowledgeAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkAcknowledgeAlertsResponse)
	err := c.cc.Invoke(ctx, AlertService_BulkAcknowledgeAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) BulkResolveAlerts(ctx context.Context, in *BulkResolveAlertsRequest, opts ...grpc.CallOption) (*BulkResolveAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResolveAlertsResponse)
	err := c.cc.Invoke(ctx, AlertService_BulkResolveAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertServiceServer is the server API for AlertService service.
// All implementations must embed UnimplementedAlertServiceServer
// for forward compatibility.
//
// AlertService provides alert management operations
type AlertServiceServer interface {
	// Create a new alert (typically from webhook)
	CreateAlert(context.Context, *CreateAlertRequest) (*Alert, error)
	// Get alert by ID
	GetAlert(context.Context, *GetAlertRequest) (*Alert, error)
	// List alerts with filters
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	// Update alert (limited fields)
	UpdateAlert(context.Context, *UpdateAlertRequest) (*Alert, error)
	// Acknowledge an alert
	AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*Alert, error)
	// Resolve an alert
	ResolveAlert(context.Context, *ResolveAlertRequest) (*Alert, error)
	// Escalate alert to policy
	EscalateAlert(context.Context, *EscalateAlertRequest) (*Alert, error)
	// Add note to alert
	AddNote(context.Context, *AddNoteRequest) (*Alert, error)
	// Get alert events/history
	GetAlertEvents(context.Context, *GetAlertEventsRequest) (*GetAlertEventsResponse, error)
	// Bulk acknowledge alerts
	BulkAcknowledgeAlerts(context.Context, *BulkAcknowledgeAlertsRequest) (*BulkAcknowledgeAlertsResponse, error)
	// Bulk resolve alerts
	BulkResolveAlerts(context.Context, *BulkResolveAlertsRequest) (*BulkResolveAlertsResponse, error)
	mustEmbedUnimplementedAlertServiceServer()
}

// UnimplementedAlertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertServiceServer struct{}

func (UnimplementedAlertServiceServer) CreateAlert(context.Context, *CreateAlertRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlert not implemented")
}
func (UnimplementedAlertServiceServer) GetAlert(context.Context, *GetAlertRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedAlertServiceServer) ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedAlertServiceServer) UpdateAlert(context.Context, *UpdateAlertRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAlert not implemented")
}
func (UnimplementedAlertServiceServer) AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeAlert not implemented")
}
func (UnimplementedAlertServiceServer) ResolveAlert(context.Context, *ResolveAlertRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAlert not implemented")
}
func (UnimplementedAlertServiceServer) EscalateAlert(context.Context, *EscalateAlertRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method EscalateAlert not implemented")
}
func (UnimplementedAlertServiceServer) AddNote(context.Context, *AddNoteRequest) (*Alert, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNote not implemented")
}
func (UnimplementedAlertServiceServer) GetAlertEvents(context.Context, *GetAlertEventsRequest) (*GetAlertEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertEvents not implemented")
}
func (UnimplementedAlertServiceServer) BulkAcknowledgeAlerts(context.Context, *BulkAcknowledgeAlertsRequest) (*BulkAcknowledgeAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkAcknowledgeAlerts not implemented")
}
func (UnimplementedAlertServiceServer) BulkResolveAlerts(context.Context, *BulkResolveAlertsRequest) (*BulkResolveAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkResolveAlerts not implemented")
}
func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}
func (UnimplementedAlertServiceServer) testEmbeddedByValue()                      {}

// UnsafeAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertServiceServer will
// result in compilation errors.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	// If the following call panics, it indicates UnimplementedAlertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_CreateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_UpdateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).UpdateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_UpdateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).UpdateAlert(ctx, req.(*UpdateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_AcknowledgeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).AcknowledgeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_AcknowledgeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).AcknowledgeAlert(ctx, req.(*AcknowledgeAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_ResolveAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).ResolveAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_ResolveAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).ResolveAlert(ctx, req.(*ResolveAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_EscalateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscalateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).EscalateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_EscalateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).EscalateAlert(ctx, req.(*EscalateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_AddNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).AddNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_AddNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).AddNote(ctx, req.(*AddNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_GetAlertEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).GetAlertEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_GetAlertEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).GetAlertEvents(ctx, req.(*GetAlertEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_BulkAcknowledgeAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkAcknowledgeAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).BulkAcknowledgeAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_BulkAcknowledgeAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).BulkAcknowledgeAlerts(ctx, req.(*BulkAcknowledgeAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_BulkResolveAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkResolveAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).BulkResolveAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_BulkResolveAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).BulkResolveAlerts(ctx, req.(*BulkResolveAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerting.v1.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlert",
			Handler:    _AlertService_CreateAlert_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _AlertService_GetAlert_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _AlertService_ListAlerts_Handler,
		},
		{
			MethodName: "UpdateAlert",
			Handler:    _AlertService_UpdateAlert_Handler,
		},
		{
			MethodName: "AcknowledgeAlert",
			Handler:    _AlertService_AcknowledgeAlert_Handler,
		},
		{
			MethodName: "ResolveAlert",
			Handler:    _AlertService_ResolveAlert_Handler,
		},
		{
			MethodName: "EscalateAlert",
			Handler:    _AlertService_EscalateAlert_Handler,
		},
		{
			MethodName: "AddNote",
			Handler:    _AlertService_AddNote_Handler,
		},
		{
			MethodName: "GetAlertEvents",
			Handler:    _AlertService_GetAlertEvents_Handler,
		},
		{
			MethodName: "BulkAcknowledgeAlerts",
			Handler:    _AlertService_BulkAcknowledgeAlerts_Handler,
		},
		{
			MethodName: "BulkResolveAlerts",
			Handler:    _AlertService_BulkResolveAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alerting/v1/alert_service.proto",
}
