// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notification/v1/notification_service.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_notification_v1_notification_service_proto protoreflect.FileDescriptor

const file_notification_v1_notification_service_proto_rawDesc = "" +
	"\n" +
	"*notification/v1/notification_service.proto\x12\x0fnotification.v1\x1a\"notification/v1/notification.proto\x1a\x1enotification/v1/template.proto2\xce\x02\n" +
	"\x13NotificationService\x12g\n" +
	"\x10SendNotification\x12(.notification.v1.SendNotificationRequest\x1a).notification.v1.SendNotificationResponse\x12_\n" +
	"\x11GetDeliveryStatus\x12).notification.v1.GetDeliveryStatusRequest\x1a\x1f.notification.v1.DeliveryStatus\x12m\n" +
	"\x12ListDeliveryStatus\x12*.notification.v1.ListDeliveryStatusRequest\x1a+.notification.v1.ListDeliveryStatusResponse2\x8e\x05\n" +
	"\x0fTemplateService\x12S\n" +
	"\x0eCreateTemplate\x12&.notification.v1.CreateTemplateRequest\x1a\x19.notification.v1.Template\x12M\n" +
	"\vGetTemplate\x12#.notification.v1.GetTemplateRequest\x1a\x19.notification.v1.Template\x12S\n" +
	"\x0eUpdateTemplate\x12&.notification.v1.UpdateTemplateRequest\x1a\x19.notification.v1.Template\x12a\n" +
	"\x0eDeleteTemplate\x12&.notification.v1.DeleteTemplateRequest\x1a'.notification.v1.DeleteTemplateResponse\x12^\n" +
	"\rListTemplates\x12%.notification.v1.ListTemplatesRequest\x1a&.notification.v1.ListTemplatesResponse\x12^\n" +
	"\rRenderPreview\x12%.notification.v1.RenderPreviewRequest\x1a&.notification.v1.RenderPreviewResponse\x12_\n" +
	"\x10ValidateTemplate\x12(.notification.v1.ValidateTemplateRequest\x1a!.notification.v1.ValidationResultB\xde\x01\n" +
	"\x13com.notification.v1B\x18NotificationServiceProtoP\x01ZPgithub.com/kneutral-org/alerting-system/pkg/proto/notification/v1;notificationv1\xa2\x02\x03NXX\xaa\x02\x0fNotification.V1\xca\x02\x0fNotification\\V1\xe2\x02\x1bNotification\\V1\\GPBMetadata\xea\x02\x10Notification::V1b\x06proto3"

var file_notification_v1_notification_service_proto_goTypes = []any{
	(*SendNotificationRequest)(nil),    // 0: notification.v1.SendNotificationRequest
	(*GetDeliveryStatusRequest)(nil),   // 1: notification.v1.GetDeliveryStatusRequest
	(*ListDeliveryStatusRequest)(nil),  // 2: notification.v1.ListDeliveryStatusRequest
	(*CreateTemplateRequest)(nil),      // 3: notification.v1.CreateTemplateRequest
	(*GetTemplateRequest)(nil),         // 4: notification.v1.GetTemplateRequest
	(*UpdateTemplateRequest)(nil),      // 5: notification.v1.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),      // 6: notification.v1.DeleteTemplateRequest
	(*ListTemplatesRequest)(nil),       // 7: notification.v1.ListTemplatesRequest
	(*RenderPreviewRequest)(nil),       // 8: notification.v1.RenderPreviewRequest
	(*ValidateTemplateRequest)(nil),    // 9: notification.v1.ValidateTemplateRequest
	(*SendNotificationResponse)(nil),   // 10: notification.v1.SendNotificationResponse
	(*DeliveryStatus)(nil),             // 11: notification.v1.DeliveryStatus
	(*ListDeliveryStatusResponse)(nil), // 12: notification.v1.ListDeliveryStatusResponse
	(*Template)(nil),                   // 13: notification.v1.Template
	(*DeleteTemplateResponse)(nil),     // 14: notification.v1.DeleteTemplateResponse
	(*ListTemplatesResponse)(nil),      // 15: notification.v1.ListTemplatesResponse
	(*RenderPreviewResponse)(nil),      // 16: notification.v1.RenderPreviewResponse
	(*ValidationResult)(nil),           // 17: notification.v1.ValidationResult
}
var file_notification_v1_notification_service_proto_depIdxs = []int32{
	0,  // 0: notification.v1.NotificationService.SendNotification:input_type -> notification.v1.SendNotificationRequest
	1,  // 1: notification.v1.NotificationService.GetDeliveryStatus:input_type -> notification.v1.GetDeliveryStatusRequest
	2,  // 2: notification.v1.NotificationService.ListDeliveryStatus:input_type -> notification.v1.ListDeliveryStatusRequest
	3,  // 3: notification.v1.TemplateService.CreateTemplate:input_type -> notification.v1.CreateTemplateRequest
	4,  // 4: notification.v1.TemplateService.GetTemplate:input_type -> notification.v1.GetTemplateRequest
	5,  // 5: notification.v1.TemplateService.UpdateTemplate:input_type -> notification.v1.UpdateTemplateRequest
	6,  // 6: notification.v1.TemplateService.DeleteTemplate:input_type -> notification.v1.DeleteTemplateRequest
	7,  // 7: notification.v1.TemplateService.ListTemplates:input_type -> notification.v1.ListTemplatesRequest
	8,  // 8: notification.v1.TemplateService.RenderPreview:input_type -> notification.v1.RenderPreviewRequest
	9,  // 9: notification.v1.TemplateService.ValidateTemplate:input_type -> notification.v1.ValidateTemplateRequest
	10, // 10: notification.v1.NotificationService.SendNotification:output_type -> notification.v1.SendNotificationResponse
	11, // 11: notification.v1.NotificationService.GetDeliveryStatus:output_type -> notification.v1.DeliveryStatus
	12, // 12: notification.v1.NotificationService.ListDeliveryStatus:output_type -> notification.v1.ListDeliveryStatusResponse
	13, // 13: notification.v1.TemplateService.CreateTemplate:output_type -> notification.v1.Template
	13, // 14: notification.v1.TemplateService.GetTemplate:output_type -> notification.v1.Template
	13, // 15: notification.v1.TemplateService.UpdateTemplate:output_type -> notification.v1.Template
	14, // 16: notification.v1.TemplateService.DeleteTemplate:output_type -> notification.v1.DeleteTemplateResponse
	15, // 17: notification.v1.TemplateService.ListTemplates:output_type -> notification.v1.ListTemplatesResponse
	16, // 18: notification.v1.TemplateService.RenderPreview:output_type -> notification.v1.RenderPreviewResponse
	17, // 19: notification.v1.TemplateService.ValidateTemplate:output_type -> notification.v1.ValidationResult
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_service_proto_init() }
func file_notification_v1_notification_service_proto_init() {
	if File_notification_v1_notification_service_proto != nil {
		return
	}
	file_notification_v1_notification_proto_init()
	file_notification_v1_template_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_service_proto_rawDesc), len(file_notification_v1_notification_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_notification_v1_notification_service_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_service_proto_depIdxs,
	}.Build()
	File_notification_v1_notification_service_proto = out.File
	file_notification_v1_notification_service_proto_goTypes = nil
	file_notification_v1_notification_service_proto_depIdxs = nil
}
