// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChannelType defines the notification delivery channels
type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED ChannelType = 0
	ChannelType_CHANNEL_TYPE_SLACK       ChannelType = 1
	ChannelType_CHANNEL_TYPE_TEAMS       ChannelType = 2
	ChannelType_CHANNEL_TYPE_EMAIL       ChannelType = 3
	ChannelType_CHANNEL_TYPE_SMS         ChannelType = 4
	ChannelType_CHANNEL_TYPE_VOICE       ChannelType = 5
	ChannelType_CHANNEL_TYPE_WEBHOOK     ChannelType = 6
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TYPE_UNSPECIFIED",
		1: "CHANNEL_TYPE_SLACK",
		2: "CHANNEL_TYPE_TEAMS",
		3: "CHANNEL_TYPE_EMAIL",
		4: "CHANNEL_TYPE_SMS",
		5: "CHANNEL_TYPE_VOICE",
		6: "CHANNEL_TYPE_WEBHOOK",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED": 0,
		"CHANNEL_TYPE_SLACK":       1,
		"CHANNEL_TYPE_TEAMS":       2,
		"CHANNEL_TYPE_EMAIL":       3,
		"CHANNEL_TYPE_SMS":         4,
		"CHANNEL_TYPE_VOICE":       5,
		"CHANNEL_TYPE_WEBHOOK":     6,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_notification_v1_notification_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

// NotificationPriority defines the urgency level of a notification
type NotificationPriority int32

const (
	NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_NOTIFICATION_PRIORITY_LOW         NotificationPriority = 1
	NotificationPriority_NOTIFICATION_PRIORITY_NORMAL      NotificationPriority = 2
	NotificationPriority_NOTIFICATION_PRIORITY_HIGH        NotificationPriority = 3
	NotificationPriority_NOTIFICATION_PRIORITY_CRITICAL    NotificationPriority = 4
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "NOTIFICATION_PRIORITY_UNSPECIFIED",
		1: "NOTIFICATION_PRIORITY_LOW",
		2: "NOTIFICATION_PRIORITY_NORMAL",
		3: "NOTIFICATION_PRIORITY_HIGH",
		4: "NOTIFICATION_PRIORITY_CRITICAL",
	}
	NotificationPriority_value = map[string]int32{
		"NOTIFICATION_PRIORITY_UNSPECIFIED": 0,
		"NOTIFICATION_PRIORITY_LOW":         1,
		"NOTIFICATION_PRIORITY_NORMAL":      2,
		"NOTIFICATION_PRIORITY_HIGH":        3,
		"NOTIFICATION_PRIORITY_CRITICAL":    4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_notification_v1_notification_proto_enumTypes[1]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

// DeliveryState represents the current state of a notification delivery
type DeliveryState int32

const (
	DeliveryState_DELIVERY_STATE_UNSPECIFIED DeliveryState = 0
	DeliveryState_DELIVERY_STATE_PENDING     DeliveryState = 1
	DeliveryState_DELIVERY_STATE_SENT        DeliveryState = 2
	DeliveryState_DELIVERY_STATE_DELIVERED   DeliveryState = 3
	DeliveryState_DELIVERY_STATE_FAILED      DeliveryState = 4
	DeliveryState_DELIVERY_STATE_RETRYING    DeliveryState = 5
)

// Enum value maps for DeliveryState.
var (
	DeliveryState_name = map[int32]string{
		0: "DELIVERY_STATE_UNSPECIFIED",
		1: "DELIVERY_STATE_PENDING",
		2: "DELIVERY_STATE_SENT",
		3: "DELIVERY_STATE_DELIVERED",
		4: "DELIVERY_STATE_FAILED",
		5: "DELIVERY_STATE_RETRYING",
	}
	DeliveryState_value = map[string]int32{
		"DELIVERY_STATE_UNSPECIFIED": 0,
		"DELIVERY_STATE_PENDING":     1,
		"DELIVERY_STATE_SENT":        2,
		"DELIVERY_STATE_DELIVERED":   3,
		"DELIVERY_STATE_FAILED":      4,
		"DELIVERY_STATE_RETRYING":    5,
	}
)

func (x DeliveryState) Enum() *DeliveryState {
	p := new(DeliveryState)
	*p = x
	return p
}

func (x DeliveryState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryState) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_notification_proto_enumTypes[2].Descriptor()
}

func (DeliveryState) Type() protoreflect.EnumType {
	return &file_notification_v1_notification_proto_enumTypes[2]
}

func (x DeliveryState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryState.Descriptor instead.
func (DeliveryState) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

// Destination specifies where a notification should be sent
type Destination struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelType    ChannelType            `protobuf:"varint,2,opt,name=channel_type,json=channelType,proto3,enum=notification.v1.ChannelType" json:"channel_type,omitempty"`
	ChannelAddress string                 `protobuf:"bytes,3,opt,name=channel_address,json=channelAddress,proto3" json:"channel_address,omitempty"` // email address, phone number, slack channel, etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Destination) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Destination) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *Destination) GetChannelAddress() string {
	if x != nil {
		return x.ChannelAddress
	}
	return ""
}

// SendNotificationRequest is the request to send a notification
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Idempotency key
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	RenderContext *structpb.Struct       `protobuf:"bytes,3,opt,name=render_context,json=renderContext,proto3" json:"render_context,omitempty"` // Variables for template rendering
	Destinations  []*Destination         `protobuf:"bytes,4,rep,name=destinations,proto3" json:"destinations,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,5,opt,name=priority,proto3,enum=notification.v1.NotificationPriority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendNotificationRequest) GetRenderContext() *structpb.Struct {
	if x != nil {
		return x.RenderContext
	}
	return nil
}

func (x *SendNotificationRequest) GetDestinations() []*Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *SendNotificationRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

// SendNotificationResponse is the response after queuing a notification
type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeliveryIds   []string               `protobuf:"bytes,2,rep,name=delivery_ids,json=deliveryIds,proto3" json:"delivery_ids,omitempty"` // One per destination
	QueuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendNotificationResponse) GetDeliveryIds() []string {
	if x != nil {
		return x.DeliveryIds
	}
	return nil
}

func (x *SendNotificationResponse) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

// DeliveryStatus represents the delivery status of a notification to a destination
type DeliveryStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Destination   *Destination           `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Status        DeliveryState          `protobuf:"varint,4,opt,name=status,proto3,enum=notification.v1.DeliveryState" json:"status,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	NextRetryAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryStatus) Reset() {
	*x = DeliveryStatus{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryStatus) ProtoMessage() {}

func (x *DeliveryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryStatus.ProtoReflect.Descriptor instead.
func (*DeliveryStatus) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryStatus) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeliveryStatus) GetDestination() *Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *DeliveryStatus) GetStatus() DeliveryState {
	if x != nil {
		return x.Status
	}
	return DeliveryState_DELIVERY_STATE_UNSPECIFIED
}

func (x *DeliveryStatus) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *DeliveryStatus) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *DeliveryStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryStatus) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *DeliveryStatus) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

// GetDeliveryStatusRequest requests the status of a specific delivery
type GetDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatusRequest) Reset() {
	*x = GetDeliveryStatusRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryStatusRequest) ProtoMessage() {}

func (x *GetDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveryStatusRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

// ListDeliveryStatusRequest requests delivery statuses with filters
type ListDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                     // Filter by original request
	States        []DeliveryState        `protobuf:"varint,2,rep,packed,name=states,proto3,enum=notification.v1.DeliveryState" json:"states,omitempty"` // Filter by delivery states
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryStatusRequest) Reset() {
	*x = ListDeliveryStatusRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryStatusRequest) ProtoMessage() {}

func (x *ListDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListDeliveryStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListDeliveryStatusRequest) GetStates() []DeliveryState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListDeliveryStatusRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDeliveryStatusRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListDeliveryStatusResponse contains a list of delivery statuses
type ListDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*DeliveryStatus      `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryStatusResponse) Reset() {
	*x = ListDeliveryStatusResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryStatusResponse) ProtoMessage() {}

func (x *ListDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListDeliveryStatusResponse) GetDeliveries() []*DeliveryStatus {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *ListDeliveryStatusResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListDeliveryStatusResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x90\x01\n" +
	"\vDestination\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12?\n" +
	"\fchannel_type\x18\x02 \x01(\x0e2\x1c.notification.v1.ChannelTypeR\vchannelType\x12'\n" +
	"\x0fchannel_address\x18\x03 \x01(\tR\x0echannelAddress\"\x9e\x02\n" +
	"\x17SendNotificationRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12>\n" +
	"\x0erender_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\rrenderContext\x12@\n" +
	"\fdestinations\x18\x04 \x03(\v2\x1c.notification.v1.DestinationR\fdestinations\x12A\n" +
	"\bpriority\x18\x05 \x01(\x0e2%.notification.v1.NotificationPriorityR\bpriority\"\x95\x01\n" +
	"\x18SendNotificationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fdelivery_ids\x18\x02 \x03(\tR\vdeliveryIds\x127\n" +
	"\tqueued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\"\xb1\x03\n" +
	"\x0eDeliveryStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12>\n" +
	"\vdestination\x18\x03 \x01(\v2\x1c.notification.v1.DestinationR\vdestination\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.notification.v1.DeliveryStateR\x06status\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12=\n" +
	"\fdelivered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12>\n" +
	"\rnext_retry_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\";\n" +
	"\x18GetDeliveryStatusRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\"\xae\x01\n" +
	"\x19ListDeliveryStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x126\n" +
	"\x06states\x18\x02 \x03(\x0e2\x1e.notification.v1.DeliveryStateR\x06states\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xa6\x01\n" +
	"\x1aListDeliveryStatusResponse\x12?\n" +
	"\n" +
	"deliveries\x18\x01 \x03(\v2\x1f.notification.v1.DeliveryStatusR\n" +
	"deliveries\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount*\xbb\x01\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHANNEL_TYPE_SLACK\x10\x01\x12\x16\n" +
	"\x12CHANNEL_TYPE_TEAMS\x10\x02\x12\x16\n" +
	"\x12CHANNEL_TYPE_EMAIL\x10\x03\x12\x14\n" +
	"\x10CHANNEL_TYPE_SMS\x10\x04\x12\x16\n" +
	"\x12CHANNEL_TYPE_VOICE\x10\x05\x12\x18\n" +
	"\x14CHANNEL_TYPE_WEBHOOK\x10\x06*\xc2\x01\n" +
	"\x14NotificationPriority\x12%\n" +
	"!NOTIFICATION_PRIORITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NOTIFICATION_PRIORITY_LOW\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_NORMAL\x10\x02\x12\x1e\n" +
	"\x1aNOTIFICATION_PRIORITY_HIGH\x10\x03\x12\"\n" +
	"\x1eNOTIFICATION_PRIORITY_CRITICAL\x10\x04*\xba\x01\n" +
	"\rDeliveryState\x12\x1e\n" +
	"\x1aDELIVERY_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DELIVERY_STATE_PENDING\x10\x01\x12\x17\n" +
	"\x13DELIVERY_STATE_SENT\x10\x02\x12\x1c\n" +
	"\x18DELIVERY_STATE_DELIVERED\x10\x03\x12\x19\n" +
	"\x15DELIVERY_STATE_FAILED\x10\x04\x12\x1b\n" +
	"\x17DELIVERY_STATE_RETRYING\x10\x05B\xd7\x01\n" +
	"\x13com.notification.v1B\x11NotificationProtoP\x01ZPgithub.com/kneutral-org/alerting-system/pkg/proto/notification/v1;notificationv1\xa2\x02\x03NXX\xaa\x02\x0fNotification.V1\xca\x02\x0fNotification\\V1\xe2\x02\x1bNotification\\V1\\GPBMetadata\xea\x02\x10Notification::V1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notification_v1_notification_proto_goTypes = []any{
	(ChannelType)(0),                   // 0: notification.v1.ChannelType
	(NotificationPriority)(0),          // 1: notification.v1.NotificationPriority
	(DeliveryState)(0),                 // 2: notification.v1.DeliveryState
	(*Destination)(nil),                // 3: notification.v1.Destination
	(*SendNotificationRequest)(nil),    // 4: notification.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil),   // 5: notification.v1.SendNotificationResponse
	(*DeliveryStatus)(nil),             // 6: notification.v1.DeliveryStatus
	(*GetDeliveryStatusRequest)(nil),   // 7: notification.v1.GetDeliveryStatusRequest
	(*ListDeliveryStatusRequest)(nil),  // 8: notification.v1.ListDeliveryStatusRequest
	(*ListDeliveryStatusResponse)(nil), // 9: notification.v1.ListDeliveryStatusResponse
	(*structpb.Struct)(nil),            // 10: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	0,  // 0: notification.v1.Destination.channel_type:type_name -> notification.v1.ChannelType
	10, // 1: notification.v1.SendNotificationRequest.render_context:type_name -> google.protobuf.Struct
	3,  // 2: notification.v1.SendNotificationRequest.destinations:type_name -> notification.v1.Destination
	1,  // 3: notification.v1.SendNotificationRequest.priority:type_name -> notification.v1.NotificationPriority
	11, // 4: notification.v1.SendNotificationResponse.queued_at:type_name -> google.protobuf.Timestamp
	3,  // 5: notification.v1.DeliveryStatus.destination:type_name -> notification.v1.Destination
	2,  // 6: notification.v1.DeliveryStatus.status:type_name -> notification.v1.DeliveryState
	11, // 7: notification.v1.DeliveryStatus.sent_at:type_name -> google.protobuf.Timestamp
	11, // 8: notification.v1.DeliveryStatus.delivered_at:type_name -> google.protobuf.Timestamp
	11, // 9: notification.v1.DeliveryStatus.next_retry_at:type_name -> google.protobuf.Timestamp
	2,  // 10: notification.v1.ListDeliveryStatusRequest.states:type_name -> notification.v1.DeliveryState
	6,  // 11: notification.v1.ListDeliveryStatusResponse.deliveries:type_name -> notification.v1.DeliveryStatus
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
