// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notification/v1/template.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TemplateFormat defines the format of template content
type TemplateFormat int32

const (
	TemplateFormat_TEMPLATE_FORMAT_UNSPECIFIED         TemplateFormat = 0
	TemplateFormat_TEMPLATE_FORMAT_PLAIN_TEXT          TemplateFormat = 1
	TemplateFormat_TEMPLATE_FORMAT_MARKDOWN            TemplateFormat = 2
	TemplateFormat_TEMPLATE_FORMAT_HTML                TemplateFormat = 3
	TemplateFormat_TEMPLATE_FORMAT_SLACK_BLOCKS        TemplateFormat = 4
	TemplateFormat_TEMPLATE_FORMAT_TEAMS_ADAPTIVE_CARD TemplateFormat = 5
)

// Enum value maps for TemplateFormat.
var (
	TemplateFormat_name = map[int32]string{
		0: "TEMPLATE_FORMAT_UNSPECIFIED",
		1: "TEMPLATE_FORMAT_PLAIN_TEXT",
		2: "TEMPLATE_FORMAT_MARKDOWN",
		3: "TEMPLATE_FORMAT_HTML",
		4: "TEMPLATE_FORMAT_SLACK_BLOCKS",
		5: "TEMPLATE_FORMAT_TEAMS_ADAPTIVE_CARD",
	}
	TemplateFormat_value = map[string]int32{
		"TEMPLATE_FORMAT_UNSPECIFIED":         0,
		"TEMPLATE_FORMAT_PLAIN_TEXT":          1,
		"TEMPLATE_FORMAT_MARKDOWN":            2,
		"TEMPLATE_FORMAT_HTML":                3,
		"TEMPLATE_FORMAT_SLACK_BLOCKS":        4,
		"TEMPLATE_FORMAT_TEAMS_ADAPTIVE_CARD": 5,
	}
)

func (x TemplateFormat) Enum() *TemplateFormat {
	p := new(TemplateFormat)
	*p = x
	return p
}

func (x TemplateFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_template_proto_enumTypes[0].Descriptor()
}

func (TemplateFormat) Type() protoreflect.EnumType {
	return &file_notification_v1_template_proto_enumTypes[0]
}

func (x TemplateFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateFormat.Descriptor instead.
func (TemplateFormat) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{0}
}

// ChannelTemplate contains template content for a specific channel
type ChannelTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       ChannelType            `protobuf:"varint,1,opt,name=channel,proto3,enum=notification.v1.ChannelType" json:"channel,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Template content (Go template syntax)
	Format        TemplateFormat         `protobuf:"varint,3,opt,name=format,proto3,enum=notification.v1.TemplateFormat" json:"format,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Channel-specific metadata (e.g., subject for email)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelTemplate) Reset() {
	*x = ChannelTemplate{}
	mi := &file_notification_v1_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelTemplate) ProtoMessage() {}

func (x *ChannelTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelTemplate.ProtoReflect.Descriptor instead.
func (*ChannelTemplate) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelTemplate) GetChannel() ChannelType {
	if x != nil {
		return x.Channel
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *ChannelTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChannelTemplate) GetFormat() TemplateFormat {
	if x != nil {
		return x.Format
	}
	return TemplateFormat_TEMPLATE_FORMAT_UNSPECIFIED
}

func (x *ChannelTemplate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Template represents a notification template
type Template struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CurrentVersion    int32                  `protobuf:"varint,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	ChannelTemplates  []*ChannelTemplate     `protobuf:"bytes,5,rep,name=channel_templates,json=channelTemplates,proto3" json:"channel_templates,omitempty"`
	RequiredVariables []string               `protobuf:"bytes,6,rep,name=required_variables,json=requiredVariables,proto3" json:"required_variables,omitempty"` // Variables that must be provided
	OptionalVariables []string               `protobuf:"bytes,7,rep,name=optional_variables,json=optionalVariables,proto3" json:"optional_variables,omitempty"` // Variables that may be provided
	CreatedByUserId   string                 `protobuf:"bytes,8,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_notification_v1_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{1}
}

func (x *Template) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Template) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *Template) GetChannelTemplates() []*ChannelTemplate {
	if x != nil {
		return x.ChannelTemplates
	}
	return nil
}

func (x *Template) GetRequiredVariables() []string {
	if x != nil {
		return x.RequiredVariables
	}
	return nil
}

func (x *Template) GetOptionalVariables() []string {
	if x != nil {
		return x.OptionalVariables
	}
	return nil
}

func (x *Template) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

func (x *Template) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Template) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RenderedPreview contains the rendered output for a channel
type RenderedPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       ChannelType            `protobuf:"varint,1,opt,name=channel,proto3,enum=notification.v1.ChannelType" json:"channel,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Format        TemplateFormat         `protobuf:"varint,3,opt,name=format,proto3,enum=notification.v1.TemplateFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderedPreview) Reset() {
	*x = RenderedPreview{}
	mi := &file_notification_v1_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderedPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderedPreview) ProtoMessage() {}

func (x *RenderedPreview) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderedPreview.ProtoReflect.Descriptor instead.
func (*RenderedPreview) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{2}
}

func (x *RenderedPreview) GetChannel() ChannelType {
	if x != nil {
		return x.Channel
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *RenderedPreview) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RenderedPreview) GetFormat() TemplateFormat {
	if x != nil {
		return x.Format
	}
	return TemplateFormat_TEMPLATE_FORMAT_UNSPECIFIED
}

// ValidationResult contains the result of template validation
type ValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_notification_v1_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{3}
}

func (x *ValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidationResult) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// RenderPreviewRequest requests a preview of a rendered template
type RenderPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                           // 0 means current version
	SampleData    *structpb.Struct       `protobuf:"bytes,3,opt,name=sample_data,json=sampleData,proto3" json:"sample_data,omitempty"`                    // Sample variables for rendering
	Channels      []ChannelType          `protobuf:"varint,4,rep,packed,name=channels,proto3,enum=notification.v1.ChannelType" json:"channels,omitempty"` // Which channels to preview
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderPreviewRequest) Reset() {
	*x = RenderPreviewRequest{}
	mi := &file_notification_v1_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPreviewRequest) ProtoMessage() {}

func (x *RenderPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPreviewRequest.ProtoReflect.Descriptor instead.
func (*RenderPreviewRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{4}
}

func (x *RenderPreviewRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *RenderPreviewRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RenderPreviewRequest) GetSampleData() *structpb.Struct {
	if x != nil {
		return x.SampleData
	}
	return nil
}

func (x *RenderPreviewRequest) GetChannels() []ChannelType {
	if x != nil {
		return x.Channels
	}
	return nil
}

// RenderPreviewResponse contains rendered previews for each channel
type RenderPreviewResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Previews      map[string]*RenderedPreview `protobuf:"bytes,1,rep,name=previews,proto3" json:"previews,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key is channel name
	Validation    *ValidationResult           `protobuf:"bytes,2,opt,name=validation,proto3" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderPreviewResponse) Reset() {
	*x = RenderPreviewResponse{}
	mi := &file_notification_v1_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPreviewResponse) ProtoMessage() {}

func (x *RenderPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPreviewResponse.ProtoReflect.Descriptor instead.
func (*RenderPreviewResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{5}
}

func (x *RenderPreviewResponse) GetPreviews() map[string]*RenderedPreview {
	if x != nil {
		return x.Previews
	}
	return nil
}

func (x *RenderPreviewResponse) GetValidation() *ValidationResult {
	if x != nil {
		return x.Validation
	}
	return nil
}

// CreateTemplateRequest creates a new template
type CreateTemplateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ChannelTemplates  []*ChannelTemplate     `protobuf:"bytes,3,rep,name=channel_templates,json=channelTemplates,proto3" json:"channel_templates,omitempty"`
	RequiredVariables []string               `protobuf:"bytes,4,rep,name=required_variables,json=requiredVariables,proto3" json:"required_variables,omitempty"`
	OptionalVariables []string               `protobuf:"bytes,5,rep,name=optional_variables,json=optionalVariables,proto3" json:"optional_variables,omitempty"`
	CreatedByUserId   string                 `protobuf:"bytes,6,opt,name=created_by_user_id,json=createdByUserId,proto3" json:"created_by_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_notification_v1_template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTemplateRequest) GetChannelTemplates() []*ChannelTemplate {
	if x != nil {
		return x.ChannelTemplates
	}
	return nil
}

func (x *CreateTemplateRequest) GetRequiredVariables() []string {
	if x != nil {
		return x.RequiredVariables
	}
	return nil
}

func (x *CreateTemplateRequest) GetOptionalVariables() []string {
	if x != nil {
		return x.OptionalVariables
	}
	return nil
}

func (x *CreateTemplateRequest) GetCreatedByUserId() string {
	if x != nil {
		return x.CreatedByUserId
	}
	return ""
}

// GetTemplateRequest gets a template by ID
type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 0 means current version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_notification_v1_template_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{7}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTemplateRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UpdateTemplateRequest updates an existing template
type UpdateTemplateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ChannelTemplates  []*ChannelTemplate     `protobuf:"bytes,4,rep,name=channel_templates,json=channelTemplates,proto3" json:"channel_templates,omitempty"`
	RequiredVariables []string               `protobuf:"bytes,5,rep,name=required_variables,json=requiredVariables,proto3" json:"required_variables,omitempty"`
	OptionalVariables []string               `protobuf:"bytes,6,rep,name=optional_variables,json=optionalVariables,proto3" json:"optional_variables,omitempty"`
	UpdatedByUserId   string                 `protobuf:"bytes,7,opt,name=updated_by_user_id,json=updatedByUserId,proto3" json:"updated_by_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_notification_v1_template_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTemplateRequest) GetChannelTemplates() []*ChannelTemplate {
	if x != nil {
		return x.ChannelTemplates
	}
	return nil
}

func (x *UpdateTemplateRequest) GetRequiredVariables() []string {
	if x != nil {
		return x.RequiredVariables
	}
	return nil
}

func (x *UpdateTemplateRequest) GetOptionalVariables() []string {
	if x != nil {
		return x.OptionalVariables
	}
	return nil
}

func (x *UpdateTemplateRequest) GetUpdatedByUserId() string {
	if x != nil {
		return x.UpdatedByUserId
	}
	return ""
}

// DeleteTemplateRequest deletes a template
type DeleteTemplateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedByUserId string                 `protobuf:"bytes,2,opt,name=deleted_by_user_id,json=deletedByUserId,proto3" json:"deleted_by_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_notification_v1_template_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTemplateRequest) GetDeletedByUserId() string {
	if x != nil {
		return x.DeletedByUserId
	}
	return ""
}

// DeleteTemplateResponse confirms template deletion
type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_notification_v1_template_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTemplateResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// ListTemplatesRequest lists templates with optional filters
type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`                 // Search in name/description
	Channels      []ChannelType          `protobuf:"varint,4,rep,packed,name=channels,proto3,enum=notification.v1.ChannelType" json:"channels,omitempty"` // Filter by supported channels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_notification_v1_template_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{11}
}

func (x *ListTemplatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTemplatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTemplatesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListTemplatesRequest) GetChannels() []ChannelType {
	if x != nil {
		return x.Channels
	}
	return nil
}

// ListTemplatesResponse contains a list of templates
type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_notification_v1_template_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{12}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTemplatesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ValidateTemplateRequest validates a template without saving
type ValidateTemplateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChannelTemplates []*ChannelTemplate     `protobuf:"bytes,1,rep,name=channel_templates,json=channelTemplates,proto3" json:"channel_templates,omitempty"`
	SampleData       *structpb.Struct       `protobuf:"bytes,2,opt,name=sample_data,json=sampleData,proto3" json:"sample_data,omitempty"` // Optional sample data for validation
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateTemplateRequest) Reset() {
	*x = ValidateTemplateRequest{}
	mi := &file_notification_v1_template_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTemplateRequest) ProtoMessage() {}

func (x *ValidateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_template_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTemplateRequest.ProtoReflect.Descriptor instead.
func (*ValidateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_template_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateTemplateRequest) GetChannelTemplates() []*ChannelTemplate {
	if x != nil {
		return x.ChannelTemplates
	}
	return nil
}

func (x *ValidateTemplateRequest) GetSampleData() *structpb.Struct {
	if x != nil {
		return x.SampleData
	}
	return nil
}

var File_notification_v1_template_proto protoreflect.FileDescriptor

const file_notification_v1_template_proto_rawDesc = "" +
	"\n" +
	"\x1enotification/v1/template.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\"notification/v1/notification.proto\"\xa5\x02\n" +
	"\x0fChannelTemplate\x126\n" +
	"\achannel\x18\x01 \x01(\x0e2\x1c.notification.v1.ChannelTypeR\achannel\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x127\n" +
	"\x06format\x18\x03 \x01(\x0e2\x1f.notification.v1.TemplateFormatR\x06format\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..notification.v1.ChannelTemplate.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x03\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fcurrent_version\x18\x04 \x01(\x05R\x0ecurrentVersion\x12M\n" +
	"\x11channel_templates\x18\x05 \x03(\v2 .notification.v1.ChannelTemplateR\x10channelTemplates\x12-\n" +
	"\x12required_variables\x18\x06 \x03(\tR\x11requiredVariables\x12-\n" +
	"\x12optional_variables\x18\a \x03(\tR\x11optionalVariables\x12+\n" +
	"\x12created_by_user_id\x18\b \x01(\tR\x0fcreatedByUserId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x01\n" +
	"\x0fRenderedPreview\x126\n" +
	"\achannel\x18\x01 \x01(\x0e2\x1c.notification.v1.ChannelTypeR\achannel\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x127\n" +
	"\x06format\x18\x03 \x01(\x0e2\x1f.notification.v1.TemplateFormatR\x06format\"\\\n" +
	"\x10ValidationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\xc5\x01\n" +
	"\x14RenderPreviewRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x128\n" +
	"\vsample_data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"sampleData\x128\n" +
	"\bchannels\x18\x04 \x03(\x0e2\x1c.notification.v1.ChannelTypeR\bchannels\"\x8b\x02\n" +
	"\x15RenderPreviewResponse\x12P\n" +
	"\bpreviews\x18\x01 \x03(\v24.notification.v1.RenderPreviewResponse.PreviewsEntryR\bpreviews\x12A\n" +
	"\n" +
	"validation\x18\x02 \x01(\v2!.notification.v1.ValidationResultR\n" +
	"validation\x1a]\n" +
	"\rPreviewsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .notification.v1.RenderedPreviewR\x05value:\x028\x01\"\xa7\x02\n" +
	"\x15CreateTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12M\n" +
	"\x11channel_templates\x18\x03 \x03(\v2 .notification.v1.ChannelTemplateR\x10channelTemplates\x12-\n" +
	"\x12required_variables\x18\x04 \x03(\tR\x11requiredVariables\x12-\n" +
	"\x12optional_variables\x18\x05 \x03(\tR\x11optionalVariables\x12+\n" +
	"\x12created_by_user_id\x18\x06 \x01(\tR\x0fcreatedByUserId\">\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\xb7\x02\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12M\n" +
	"\x11channel_templates\x18\x04 \x03(\v2 .notification.v1.ChannelTemplateR\x10channelTemplates\x12-\n" +
	"\x12required_variables\x18\x05 \x03(\tR\x11requiredVariables\x12-\n" +
	"\x12optional_variables\x18\x06 \x03(\tR\x11optionalVariables\x12+\n" +
	"\x12updated_by_user_id\x18\a \x01(\tR\x0fupdatedByUserId\"T\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x12deleted_by_user_id\x18\x02 \x01(\tR\x0fdeletedByUserId\"2\n" +
	"\x16DeleteTemplateResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xaf\x01\n" +
	"\x14ListTemplatesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\x128\n" +
	"\bchannels\x18\x04 \x03(\x0e2\x1c.notification.v1.ChannelTypeR\bchannels\"\x99\x01\n" +
	"\x15ListTemplatesResponse\x127\n" +
	"\ttemplates\x18\x01 \x03(\v2\x19.notification.v1.TemplateR\ttemplates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xa2\x01\n" +
	"\x17ValidateTemplateRequest\x12M\n" +
	"\x11channel_templates\x18\x01 \x03(\v2 .notification.v1.ChannelTemplateR\x10channelTemplates\x128\n" +
	"\vsample_data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"sampleData*\xd4\x01\n" +
	"\x0eTemplateFormat\x12\x1f\n" +
	"\x1bTEMPLATE_FORMAT_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTEMPLATE_FORMAT_PLAIN_TEXT\x10\x01\x12\x1c\n" +
	"\x18TEMPLATE_FORMAT_MARKDOWN\x10\x02\x12\x18\n" +
	"\x14TEMPLATE_FORMAT_HTML\x10\x03\x12 \n" +
	"\x1cTEMPLATE_FORMAT_SLACK_BLOCKS\x10\x04\x12'\n" +
	"#TEMPLATE_FORMAT_TEAMS_ADAPTIVE_CARD\x10\x05B\xd3\x01\n" +
	"\x13com.notification.v1B\rTemplateProtoP\x01ZPgithub.com/kneutral-org/alerting-system/pkg/proto/notification/v1;notificationv1\xa2\x02\x03NXX\xaa\x02\x0fNotification.V1\xca\x02\x0fNotification\\V1\xe2\x02\x1bNotification\\V1\\GPBMetadata\xea\x02\x10Notification::V1b\x06proto3"

var (
	file_notification_v1_template_proto_rawDescOnce sync.Once
	file_notification_v1_template_proto_rawDescData []byte
)

func file_notification_v1_template_proto_rawDescGZIP() []byte {
	file_notification_v1_template_proto_rawDescOnce.Do(func() {
		file_notification_v1_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_template_proto_rawDesc), len(file_notification_v1_template_proto_rawDesc)))
	})
	return file_notification_v1_template_proto_rawDescData
}

var file_notification_v1_template_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_v1_template_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_notification_v1_template_proto_goTypes = []any{
	(TemplateFormat)(0),             // 0: notification.v1.TemplateFormat
	(*ChannelTemplate)(nil),         // 1: notification.v1.ChannelTemplate
	(*Template)(nil),                // 2: notification.v1.Template
	(*RenderedPreview)(nil),         // 3: notification.v1.RenderedPreview
	(*ValidationResult)(nil),        // 4: notification.v1.ValidationResult
	(*RenderPreviewRequest)(nil),    // 5: notification.v1.RenderPreviewRequest
	(*RenderPreviewResponse)(nil),   // 6: notification.v1.RenderPreviewResponse
	(*CreateTemplateRequest)(nil),   // 7: notification.v1.CreateTemplateRequest
	(*GetTemplateRequest)(nil),      // 8: notification.v1.GetTemplateRequest
	(*UpdateTemplateRequest)(nil),   // 9: notification.v1.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),   // 10: notification.v1.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil),  // 11: notification.v1.DeleteTemplateResponse
	(*ListTemplatesRequest)(nil),    // 12: notification.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),   // 13: notification.v1.ListTemplatesResponse
	(*ValidateTemplateRequest)(nil), // 14: notification.v1.ValidateTemplateRequest
	nil,                             // 15: notification.v1.ChannelTemplate.MetadataEntry
	nil,                             // 16: notification.v1.RenderPreviewResponse.PreviewsEntry
	(ChannelType)(0),                // 17: notification.v1.ChannelType
	(*timestamppb.Timestamp)(nil),   // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 19: google.protobuf.Struct
}
var file_notification_v1_template_proto_depIdxs = []int32{
	17, // 0: notification.v1.ChannelTemplate.channel:type_name -> notification.v1.ChannelType
	0,  // 1: notification.v1.ChannelTemplate.format:type_name -> notification.v1.TemplateFormat
	15, // 2: notification.v1.ChannelTemplate.metadata:type_name -> notification.v1.ChannelTemplate.MetadataEntry
	1,  // 3: notification.v1.Template.channel_templates:type_name -> notification.v1.ChannelTemplate
	18, // 4: notification.v1.Template.created_at:type_name -> google.protobuf.Timestamp
	18, // 5: notification.v1.Template.updated_at:type_name -> google.protobuf.Timestamp
	17, // 6: notification.v1.RenderedPreview.channel:type_name -> notification.v1.ChannelType
	0,  // 7: notification.v1.RenderedPreview.format:type_name -> notification.v1.TemplateFormat
	19, // 8: notification.v1.RenderPreviewRequest.sample_data:type_name -> google.protobuf.Struct
	17, // 9: notification.v1.RenderPreviewRequest.channels:type_name -> notification.v1.ChannelType
	16, // 10: notification.v1.RenderPreviewResponse.previews:type_name -> notification.v1.RenderPreviewResponse.PreviewsEntry
	4,  // 11: notification.v1.RenderPreviewResponse.validation:type_name -> notification.v1.ValidationResult
	1,  // 12: notification.v1.CreateTemplateRequest.channel_templates:type_name -> notification.v1.ChannelTemplate
	1,  // 13: notification.v1.UpdateTemplateRequest.channel_templates:type_name -> notification.v1.ChannelTemplate
	17, // 14: notification.v1.ListTemplatesRequest.channels:type_name -> notification.v1.ChannelType
	2,  // 15: notification.v1.ListTemplatesResponse.templates:type_name -> notification.v1.Template
	1,  // 16: notification.v1.ValidateTemplateRequest.channel_templates:type_name -> notification.v1.ChannelTemplate
	19, // 17: notification.v1.ValidateTemplateRequest.sample_data:type_name -> google.protobuf.Struct
	3,  // 18: notification.v1.RenderPreviewResponse.PreviewsEntry.value:type_name -> notification.v1.RenderedPreview
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_notification_v1_template_proto_init() }
func file_notification_v1_template_proto_init() {
	if File_notification_v1_template_proto != nil {
		return
	}
	file_notification_v1_notification_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_template_proto_rawDesc), len(file_notification_v1_template_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_v1_template_proto_goTypes,
		DependencyIndexes: file_notification_v1_template_proto_depIdxs,
		EnumInfos:         file_notification_v1_template_proto_enumTypes,
		MessageInfos:      file_notification_v1_template_proto_msgTypes,
	}.Build()
	File_notification_v1_template_proto = out.File
	file_notification_v1_template_proto_goTypes = nil
	file_notification_v1_template_proto_depIdxs = nil
}
