// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TeamRole string

const (
	TeamRoleMember  TeamRole = "member"
	TeamRoleLead    TeamRole = "lead"
	TeamRoleManager TeamRole = "manager"
)

func (e *TeamRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRole(s)
	case string:
		*e = TeamRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRole: %T", src)
	}
	return nil
}

type NullTeamRole struct {
	TeamRole TeamRole `json:"teamRole"`
	Valid    bool     `json:"valid"` // Valid is true if TeamRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRole), nil
}

type EscalationPolicy struct {
	ID                    uuid.UUID   `json:"id"`
	Name                  string      `json:"name"`
	Description           pgtype.Text `json:"description"`
	RepeatCount           int32       `json:"repeatCount"`
	RepeatIntervalSeconds int32       `json:"repeatIntervalSeconds"`
	CreatedAt             time.Time   `json:"createdAt"`
	UpdatedAt             time.Time   `json:"updatedAt"`
}

type RoutingRule struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	Description   pgtype.Text     `json:"description"`
	Priority      int32           `json:"priority"`
	Enabled       bool            `json:"enabled"`
	Conditions    json.RawMessage `json:"conditions"`
	Actions       json.RawMessage `json:"actions"`
	Terminal      bool            `json:"terminal"`
	TimeCondition []byte          `json:"timeCondition"`
	Tags          []string        `json:"tags"`
	CreatedBy     pgtype.UUID     `json:"createdBy"`
	CreatedAt     time.Time       `json:"createdAt"`
	UpdatedBy     pgtype.UUID     `json:"updatedBy"`
	UpdatedAt     time.Time       `json:"updatedAt"`
}

type Team struct {
	ID                        uuid.UUID       `json:"id"`
	Name                      string          `json:"name"`
	Description               pgtype.Text     `json:"description"`
	DefaultEscalationPolicyID pgtype.UUID     `json:"defaultEscalationPolicyId"`
	DefaultChannel            []byte          `json:"defaultChannel"`
	AssignedSites             []string        `json:"assignedSites"`
	AssignedPops              []string        `json:"assignedPops"`
	Metadata                  json.RawMessage `json:"metadata"`
	CreatedAt                 time.Time       `json:"createdAt"`
	UpdatedAt                 time.Time       `json:"updatedAt"`
}

type TeamMember struct {
	TeamID      uuid.UUID `json:"teamId"`
	UserID      uuid.UUID `json:"userId"`
	Role        TeamRole  `json:"role"`
	Preferences []byte    `json:"preferences"`
	JoinedAt    time.Time `json:"joinedAt"`
}
