// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CreateRoutingRule(ctx context.Context, arg CreateRoutingRuleParams) (RoutingRule, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	DeleteRoutingRule(ctx context.Context, id uuid.UUID) error
	DeleteTeam(ctx context.Context, id uuid.UUID) error
	GetEnabledRulesByPriority(ctx context.Context) ([]RoutingRule, error)
	GetRoutingRule(ctx context.Context, id uuid.UUID) (RoutingRule, error)
	GetRoutingRulesByTags(ctx context.Context, tags []string) ([]RoutingRule, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error)
	GetTeamMembers(ctx context.Context, teamID uuid.UUID) ([]TeamMember, error)
	GetTeamsByEscalationPolicy(ctx context.Context, policyID pgtype.UUID) ([]Team, error)
	GetUserTeams(ctx context.Context, userID uuid.UUID) ([]Team, error)
	ListRoutingRules(ctx context.Context, arg ListRoutingRulesParams) ([]RoutingRule, error)
	ListRoutingRulesCount(ctx context.Context, arg ListRoutingRulesCountParams) (int64, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error)
	ListTeamsCount(ctx context.Context, arg ListTeamsCountParams) (int64, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	UpdateRoutingRule(ctx context.Context, arg UpdateRoutingRuleParams) (RoutingRule, error)
	UpdateRoutingRulePriority(ctx context.Context, arg UpdateRoutingRulePriorityParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) error
}

var _ Querier = (*Queries)(nil)
